//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocont.ISZRDemo.IszrAsyncOdpovedZFronty {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:cz:isvs:iszr:services:IszrAsyncOdpovedZFronty:v1", ConfigurationName="IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyPortType")]
    public interface IszrAsyncOdpovedZFrontyPortType {
        
        // CODEGEN: Generating message contract since the operation IszrAsyncOdpovedZFronty is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="IszrAsyncOdpovedZFronty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BinarniDataType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OdpovedInfoType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ZadostInfoType))]
        Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyResponse IszrAsyncOdpovedZFronty(Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncOdpovedZFronty:v1")]
    public partial class IszrAsyncOdpovedZFrontyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kodAsyncSluzbyField;
        
        private ZadostInfoIszrType zadostInfoField;
        
        private IszrAsyncOdpovedZFrontyTypeZadost zadostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN", Order=0)]
        public string KodAsyncSluzby {
            get {
                return this.kodAsyncSluzbyField;
            }
            set {
                this.kodAsyncSluzbyField = value;
                this.RaisePropertyChanged("KodAsyncSluzby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ZadostInfoIszrType ZadostInfo {
            get {
                return this.zadostInfoField;
            }
            set {
                this.zadostInfoField = value;
                this.RaisePropertyChanged("ZadostInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IszrAsyncOdpovedZFrontyTypeZadost Zadost {
            get {
                return this.zadostField;
            }
            set {
                this.zadostField = value;
                this.RaisePropertyChanged("Zadost");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public partial class ZadostInfoIszrType : ZadostInfoType {
        
        private int prioritaAisField;
        
        private bool prioritaAisFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PrioritaAis {
            get {
                return this.prioritaAisField;
            }
            set {
                this.prioritaAisField = value;
                this.RaisePropertyChanged("PrioritaAis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritaAisSpecified {
            get {
                return this.prioritaAisFieldSpecified;
            }
            set {
                this.prioritaAisFieldSpecified = value;
                this.RaisePropertyChanged("PrioritaAisSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZadostInfoIszrType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class ZadostInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime casZadostiField;
        
        private string agendaField;
        
        private string agendovaRoleField;
        
        private string ovmField;
        
        private int aisField;
        
        private bool aisFieldSpecified;
        
        private string subjektField;
        
        private string uzivatelField;
        
        private string duvodUcelField;
        
        private string agendaZadostIdField;
        
        private string predchoziZadostIdField;
        
        private string iszrZadostIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime CasZadosti {
            get {
                return this.casZadostiField;
            }
            set {
                this.casZadostiField = value;
                this.RaisePropertyChanged("CasZadosti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN", Order=1)]
        public string Agenda {
            get {
                return this.agendaField;
            }
            set {
                this.agendaField = value;
                this.RaisePropertyChanged("Agenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN", Order=2)]
        public string AgendovaRole {
            get {
                return this.agendovaRoleField;
            }
            set {
                this.agendovaRoleField = value;
                this.RaisePropertyChanged("AgendovaRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN", Order=3)]
        public string Ovm {
            get {
                return this.ovmField;
            }
            set {
                this.ovmField = value;
                this.RaisePropertyChanged("Ovm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Ais {
            get {
                return this.aisField;
            }
            set {
                this.aisField = value;
                this.RaisePropertyChanged("Ais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AisSpecified {
            get {
                return this.aisFieldSpecified;
            }
            set {
                this.aisFieldSpecified = value;
                this.RaisePropertyChanged("AisSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Subjekt {
            get {
                return this.subjektField;
            }
            set {
                this.subjektField = value;
                this.RaisePropertyChanged("Subjekt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Uzivatel {
            get {
                return this.uzivatelField;
            }
            set {
                this.uzivatelField = value;
                this.RaisePropertyChanged("Uzivatel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DuvodUcel {
            get {
                return this.duvodUcelField;
            }
            set {
                this.duvodUcelField = value;
                this.RaisePropertyChanged("DuvodUcel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AgendaZadostId {
            get {
                return this.agendaZadostIdField;
            }
            set {
                this.agendaZadostIdField = value;
                this.RaisePropertyChanged("AgendaZadostId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PredchoziZadostId {
            get {
                return this.predchoziZadostIdField;
            }
            set {
                this.predchoziZadostIdField = value;
                this.RaisePropertyChanged("PredchoziZadostId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string IszrZadostId {
            get {
                return this.iszrZadostIdField;
            }
            set {
                this.iszrZadostIdField = value;
                this.RaisePropertyChanged("IszrZadostId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class AsyncDotazDataResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2004/08/xop/include")]
    public partial class Include : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private string hrefField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
                this.RaisePropertyChanged("href");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KomprimovanaDataType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class BinarniDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Base64Data", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Include", typeof(Include), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class KomprimovanaDataType : BinarniDataType {
        
        private MetodaKompreseType metodaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MetodaKompreseType metoda {
            get {
                return this.metodaField;
            }
            set {
                this.metodaField = value;
                this.RaisePropertyChanged("metoda");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public enum MetodaKompreseType {
        
        /// <remarks/>
        zadna,
        
        /// <remarks/>
        gzip,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class SystemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Agenda", typeof(string), DataType="NMTOKEN", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Ais", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Registr", typeof(SystemTypeRegistr), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public enum SystemTypeRegistr {
        
        /// <remarks/>
        ISZR,
        
        /// <remarks/>
        RPP,
        
        /// <remarks/>
        ROB,
        
        /// <remarks/>
        ROS,
        
        /// <remarks/>
        RUIAN,
        
        /// <remarks/>
        ORG,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class StatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VysledekKodType vysledekKodField;
        
        private StatusTypeVysledekDetail[] vysledekDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VysledekKodType VysledekKod {
            get {
                return this.vysledekKodField;
            }
            set {
                this.vysledekKodField = value;
                this.RaisePropertyChanged("VysledekKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VysledekDetail", Order=1)]
        public StatusTypeVysledekDetail[] VysledekDetail {
            get {
                return this.vysledekDetailField;
            }
            set {
                this.vysledekDetailField = value;
                this.RaisePropertyChanged("VysledekDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public enum VysledekKodType {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        CHYBA,
        
        /// <remarks/>
        VAROVANI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class StatusTypeVysledekDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VysledekSubKodType vysledekSubKodField;
        
        private string vysledekPopisField;
        
        private SystemType puvodceField;
        
        private SystemType prijemceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VysledekSubKodType VysledekSubKod {
            get {
                return this.vysledekSubKodField;
            }
            set {
                this.vysledekSubKodField = value;
                this.RaisePropertyChanged("VysledekSubKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VysledekPopis {
            get {
                return this.vysledekPopisField;
            }
            set {
                this.vysledekPopisField = value;
                this.RaisePropertyChanged("VysledekPopis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SystemType Puvodce {
            get {
                return this.puvodceField;
            }
            set {
                this.puvodceField = value;
                this.RaisePropertyChanged("Puvodce");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SystemType Prijemce {
            get {
                return this.prijemceField;
            }
            set {
                this.prijemceField = value;
                this.RaisePropertyChanged("Prijemce");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public enum VysledekSubKodType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PREKROCEN CAS")]
        PREKROCENCAS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PREKROCEN SEZNAM")]
        PREKROCENSEZNAM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NENI OPRAVNENI EGON")]
        NENIOPRAVNENIEGON,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NENI OPRAVNENI")]
        NENIOPRAVNENI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("AIFO NEEXISTUJE")]
        AIFONEEXISTUJE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("AIFO ZRUSENO")]
        AIFOZRUSENO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ZIFO ZRUSENO")]
        ZIFOZRUSENO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ADRESA NEEXISTUJE")]
        ADRESANEEXISTUJE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ADRESA SMAZANA")]
        ADRESASMAZANA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("JENOM ASYNC")]
        JENOMASYNC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MIMO PORADI")]
        MIMOPORADI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NEPLATNY CAS")]
        NEPLATNYCAS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("STARSI VERZE")]
        STARSIVERZE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NEPLATNA VERZE")]
        NEPLATNAVERZE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DUPLICITNI ZADOST")]
        DUPLICITNIZADOST,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NENI IMPLEMENTOVANO")]
        NENIIMPLEMENTOVANO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NENI K DISPOZICI")]
        NENIKDISPOZICI,
        
        /// <remarks/>
        NENALEZENO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PROBIHA ZPRACOVANI")]
        PROBIHAZPRACOVANI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NEVALIDNI DATA")]
        NEVALIDNIDATA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NEVALIDNI ZADOST")]
        NEVALIDNIZADOST,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("APLIKACNI CHYBA")]
        APLIKACNICHYBA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CHYBA VOLANI REGISTRU")]
        CHYBAVOLANIREGISTRU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CHYBA VOLANI AIS")]
        CHYBAVOLANIAIS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SPECIFIKACE V POPISU")]
        SPECIFIKACEVPOPISU,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OdpovedInfoZFrontyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class OdpovedInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime casOdpovediField;
        
        private StatusType statusField;
        
        private string agendaZadostIdField;
        
        private string iszrZadostIdField;
        
        private string regOdpovedIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime CasOdpovedi {
            get {
                return this.casOdpovediField;
            }
            set {
                this.casOdpovediField = value;
                this.RaisePropertyChanged("CasOdpovedi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AgendaZadostId {
            get {
                return this.agendaZadostIdField;
            }
            set {
                this.agendaZadostIdField = value;
                this.RaisePropertyChanged("AgendaZadostId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IszrZadostId {
            get {
                return this.iszrZadostIdField;
            }
            set {
                this.iszrZadostIdField = value;
                this.RaisePropertyChanged("IszrZadostId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RegOdpovedId {
            get {
                return this.regOdpovedIdField;
            }
            set {
                this.regOdpovedIdField = value;
                this.RaisePropertyChanged("RegOdpovedId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncOdpovedZFronty:v1")]
    public partial class OdpovedInfoZFrontyType : OdpovedInfoType {
        
        private int cekaciCasField;
        
        private bool cekaciCasFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CekaciCas {
            get {
                return this.cekaciCasField;
            }
            set {
                this.cekaciCasField = value;
                this.RaisePropertyChanged("CekaciCas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CekaciCasSpecified {
            get {
                return this.cekaciCasFieldSpecified;
            }
            set {
                this.cekaciCasFieldSpecified = value;
                this.RaisePropertyChanged("CekaciCasSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncOdpovedZFronty:v1")]
    public partial class IszrAsyncOdpovedZFrontyResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kodAsyncSluzbyField;
        
        private OdpovedInfoZFrontyType odpovedInfoField;
        
        private IszrAsyncOdpovedZFrontyResponseTypeIszrOdpoved iszrOdpovedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN", Order=0)]
        public string KodAsyncSluzby {
            get {
                return this.kodAsyncSluzbyField;
            }
            set {
                this.kodAsyncSluzbyField = value;
                this.RaisePropertyChanged("KodAsyncSluzby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OdpovedInfoZFrontyType OdpovedInfo {
            get {
                return this.odpovedInfoField;
            }
            set {
                this.odpovedInfoField = value;
                this.RaisePropertyChanged("OdpovedInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IszrAsyncOdpovedZFrontyResponseTypeIszrOdpoved IszrOdpoved {
            get {
                return this.iszrOdpovedField;
            }
            set {
                this.iszrOdpovedField = value;
                this.RaisePropertyChanged("IszrOdpoved");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncOdpovedZFronty:v1")]
    public partial class IszrAsyncOdpovedZFrontyResponseTypeIszrOdpoved : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IszrAsyncOdpovedZFrontyResponseTypeIszrOdpovedIszrAsyncOdpovedZFrontyDataResponse iszrAsyncOdpovedZFrontyDataResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IszrAsyncOdpovedZFrontyResponseTypeIszrOdpovedIszrAsyncOdpovedZFrontyDataResponse IszrAsyncOdpovedZFrontyDataResponse {
            get {
                return this.iszrAsyncOdpovedZFrontyDataResponseField;
            }
            set {
                this.iszrAsyncOdpovedZFrontyDataResponseField = value;
                this.RaisePropertyChanged("IszrAsyncOdpovedZFrontyDataResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncOdpovedZFronty:v1")]
    public partial class IszrAsyncOdpovedZFrontyResponseTypeIszrOdpovedIszrAsyncOdpovedZFrontyDataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AsyncDotazDataResponse", typeof(AsyncDotazDataResponseType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KomprimovanaData", typeof(KomprimovanaDataType), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncOdpovedZFronty:v1")]
    public partial class IszrAsyncOdpovedZFrontyTypeZadost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IszrAsyncOdpovedZFrontyTypeZadostIszrAsyncOdpovedZFrontyData iszrAsyncOdpovedZFrontyDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IszrAsyncOdpovedZFrontyTypeZadostIszrAsyncOdpovedZFrontyData IszrAsyncOdpovedZFrontyData {
            get {
                return this.iszrAsyncOdpovedZFrontyDataField;
            }
            set {
                this.iszrAsyncOdpovedZFrontyDataField = value;
                this.RaisePropertyChanged("IszrAsyncOdpovedZFrontyData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncOdpovedZFronty:v1")]
    public partial class IszrAsyncOdpovedZFrontyTypeZadostIszrAsyncOdpovedZFrontyData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iszrZadostIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IszrZadostId {
            get {
                return this.iszrZadostIdField;
            }
            set {
                this.iszrZadostIdField = value;
                this.RaisePropertyChanged("IszrZadostId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IszrAsyncOdpovedZFrontyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncOdpovedZFronty:v1", Order=0)]
        public Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyType IszrAsyncOdpovedZFronty;
        
        public IszrAsyncOdpovedZFrontyRequest() {
        }
        
        public IszrAsyncOdpovedZFrontyRequest(Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyType IszrAsyncOdpovedZFronty) {
            this.IszrAsyncOdpovedZFronty = IszrAsyncOdpovedZFronty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IszrAsyncOdpovedZFrontyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IszrAsyncOdpovedZFrontyResponse", Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncOdpovedZFronty:v1", Order=0)]
        public Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyResponseType IszrAsyncOdpovedZFrontyResponse1;
        
        public IszrAsyncOdpovedZFrontyResponse() {
        }
        
        public IszrAsyncOdpovedZFrontyResponse(Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyResponseType IszrAsyncOdpovedZFrontyResponse1) {
            this.IszrAsyncOdpovedZFrontyResponse1 = IszrAsyncOdpovedZFrontyResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IszrAsyncOdpovedZFrontyPortTypeChannel : Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IszrAsyncOdpovedZFrontyPortTypeClient : System.ServiceModel.ClientBase<Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyPortType>, Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyPortType {
        
        public IszrAsyncOdpovedZFrontyPortTypeClient() {
        }
        
        public IszrAsyncOdpovedZFrontyPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IszrAsyncOdpovedZFrontyPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IszrAsyncOdpovedZFrontyPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IszrAsyncOdpovedZFrontyPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyResponse Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyPortType.IszrAsyncOdpovedZFronty(Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyRequest request) {
            return base.Channel.IszrAsyncOdpovedZFronty(request);
        }
        
        public Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyResponseType IszrAsyncOdpovedZFronty(Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyType IszrAsyncOdpovedZFronty1) {
            Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyRequest inValue = new Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyRequest();
            inValue.IszrAsyncOdpovedZFronty = IszrAsyncOdpovedZFronty1;
            Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyResponse retVal = ((Autocont.ISZRDemo.IszrAsyncOdpovedZFronty.IszrAsyncOdpovedZFrontyPortType)(this)).IszrAsyncOdpovedZFronty(inValue);
            return retVal.IszrAsyncOdpovedZFrontyResponse1;
        }
    }
}
