<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekCastObceKDatu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekCastObceKDatu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekCastObceKDatu:v1"
	xmlns:e67c="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekCastObceKDatu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrIsuiCtiPrvekCastObceKDatu">

	<wsdl:documentation>Služba E67C externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 10.2.2011, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekCastObceKDatu:v1" schemaLocation="../xsd/IszrIsuiCtiPrvekCastObceKDatu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrIsuiCtiPrvekCastObceKDatu">
		<wsdl:part name="parametry" element="e67c:IsuiCtiPrvekCastObceKDatu"/>
	</wsdl:message>
	<wsdl:message name="IszrIsuiCtiPrvekCastObceKDatuResponse">
		<wsdl:part name="vysledek" element="e67c:IsuiCtiPrvekCastObceKDatuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrIsuiCtiPrvekCastObceKDatuPortType">
		<wsdl:operation name="IszrIsuiCtiPrvekCastObceKDatu">
			<wsdl:input message="IszrIsuiCtiPrvekCastObceKDatu"/>
			<wsdl:output message="IszrIsuiCtiPrvekCastObceKDatuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrIsuiCtiPrvekCastObceKDatuBinding" type="tns:IszrIsuiCtiPrvekCastObceKDatuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrIsuiCtiPrvekCastObceKDatu">
			<soap:operation soapAction="IszrIsuiCtiPrvekCastObceKDatu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrIsuiCtiPrvekCastObceKDatuService">
		<wsdl:port name="IszrIsuiCtiPrvekCastObceKDatuPortService" binding="tns:IszrIsuiCtiPrvekCastObceKDatuBinding">
			<soap:address location="IszrIsuiCtiPrvekCastObceKDatu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
