<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRosPridelIcp:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRosPridelIcp:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRosPridelIcp:v1"
	xmlns:e17="urn:cz:isvs:iszr:schemas:IszrRosPridelIcp:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRosPridelIcp">

	<wsdl:documentation>Služba E17 externího rozhraní - Přidělení IČP na základě předepsaných identifikačních údajů - služba ROS S02.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 09.06.2011, Aleš Teplý -->
	<!-- Vývojová verze 0.0.2, 14.09.2011, Aleš Teplý, ponechání jen nezbytných namespace -->
	<!-- Fixovaná verze 1.0.0, 18.09.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRosPridelIcp:v1" schemaLocation="../xsd/IszrRosPridelIcp.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRosPridelIcp">
		<wsdl:part name="parametry" element="e17:RosPridelIcp"/>
	</wsdl:message>
	<wsdl:message name="IszrRosPridelIcpResponse">
		<wsdl:part name="vysledek" element="e17:RosPridelIcpResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRosPridelIcpPortType">
		<wsdl:operation name="IszrRosPridelIcp">
			<wsdl:input message="tns:IszrRosPridelIcp"/>
			<wsdl:output message="tns:IszrRosPridelIcpResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRosPridelIcpBinding" type="tns:IszrRosPridelIcpPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRosPridelIcp">
			<soap:operation soapAction="IszrRosPridelIcp"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRosPridelIcpService">
		<wsdl:port name="IszrRosPridelIcpPortService" binding="tns:IszrRosPridelIcpBinding">
			<soap:address location="IszrRosPridelIcp"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>