<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekCastObce:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekCastObce:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekCastObce:v1"
	xmlns:e34c="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekCastObce:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianVyhledejPrvekCastObce">

	<wsdl:documentation>Služba E34c externího rozhraní - Vyhledání časti obce z RUIAN. RUIAN služba A03, operace VyhledejCastObce.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 21.07.2011, Pavel Kirchner -->
	<!-- Fixovaná verze 1.0.0, 25.10.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekCastObce:v1" schemaLocation="../xsd/IszrRuianVyhledejPrvekCastObce.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianVyhledejPrvekCastObce">
		<wsdl:part name="parametry" element="e34c:RuianVyhledejPrvekCastObce"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianVyhledejPrvekCastObceResponse">
		<wsdl:part name="vysledek" element="e34c:RuianVyhledejPrvekCastObceResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianVyhledejPrvekCastObcePortType">
		<wsdl:operation name="IszrRuianVyhledejPrvekCastObce">
			<wsdl:input message="tns:IszrRuianVyhledejPrvekCastObce"/>
			<wsdl:output message="tns:IszrRuianVyhledejPrvekCastObceResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianVyhledejPrvekCastObceBinding" type="tns:IszrRuianVyhledejPrvekCastObcePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianVyhledejPrvekCastObce">
			<soap:operation soapAction="IszrRuianVyhledejPrvekCastObce"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianVyhledejPrvekCastObceService">
		<wsdl:port name="IszrRuianVyhledejPrvekCastObcePortService" binding="tns:IszrRuianVyhledejPrvekCastObceBinding">
			<soap:address location="IszrRuianVyhledejPrvekCastObce"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>