<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrReklamujUdajeRpp:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrReklamujUdajeRpp:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrReklamujUdajeRpp:v1"
	xmlns:e221="urn:cz:isvs:iszr:schemas:IszrReklamujUdajeRpp:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrReklamujUdajeRpp">

	<wsdl:documentation>Služba realizuje zaslání avíza o nesprávném údaji v registru RPP příslušnému editorovi údaje.</wsdl:documentation>

	<!-- Vývojová verze 1.0.0, 21.12.2016 Pavel Odstrčil, vznik -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrReklamujUdajeRpp:v1" schemaLocation="../xsd/IszrReklamujUdajeRpp.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrReklamujUdajeRpp">
		<wsdl:part name="parametry" element="e221:IszrReklamujUdajeRpp"/>
	</wsdl:message>
	<wsdl:message name="IszrReklamujUdajeRppResponse">
		<wsdl:part name="vysledek" element="e221:IszrReklamujUdajeRppResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrReklamujUdajeRppPortType">
		<wsdl:operation name="IszrReklamujUdajeRpp">
			<wsdl:input message="tns:IszrReklamujUdajeRpp"/>
			<wsdl:output message="tns:IszrReklamujUdajeRppResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrReklamujUdajeRppBinding" type="tns:IszrReklamujUdajeRppPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrReklamujUdajeRpp">
			<soap:operation soapAction="IszrReklamujUdajeRpp"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrReklamujUdajeRppService">
		<wsdl:port name="IszrReklamujUdajeRppPortService" binding="tns:IszrReklamujUdajeRppBinding">
			<soap:address location="IszrReklamujUdajeRpp"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
