<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekAdresniMisto:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekAdresniMisto:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekAdresniMisto:v1"
	xmlns:e35a="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekAdresniMisto:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiPrvekAdresniMisto">

	<wsdl:documentation>Služba E35a externího rozhraní - Načtení adresního místa z RUIAN. RUIAN služba A04, operace ctiAdresniMisto.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 24.06.2011, Aleš Teplý -->
	<!-- Vývojová verze 0.0.2, 27.07.2011, Pavel Kirchner -->
	<!-- Fixovaná verze 1.0.0, 26.10.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekAdresniMisto:v1" schemaLocation="../xsd/IszrRuianCtiPrvekAdresniMisto.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianCtiPrvekAdresniMisto">
		<wsdl:part name="parametry" element="e35a:RuianCtiPrvekAdresniMisto"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiPrvekAdresniMistoResponse">
		<wsdl:part name="vysledek" element="e35a:RuianCtiPrvekAdresniMistoResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiPrvekAdresniMistoPortType">
		<wsdl:operation name="IszrRuianCtiPrvekAdresniMisto">
			<wsdl:input message="tns:IszrRuianCtiPrvekAdresniMisto"/>
			<wsdl:output message="tns:IszrRuianCtiPrvekAdresniMistoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiPrvekAdresniMistoBinding" type="tns:IszrRuianCtiPrvekAdresniMistoPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiPrvekAdresniMisto">
			<soap:operation soapAction="IszrRuianCtiPrvekAdresniMisto"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiPrvekAdresniMistoService">
		<wsdl:port name="IszrRuianCtiPrvekAdresniMistoPortService" binding="tns:IszrRuianCtiPrvekAdresniMistoBinding">
			<soap:address location="IszrRuianCtiPrvekAdresniMisto"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>