<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns="urn:cz:isvs:iszr:services:IszrAgendaMediaDataCtiAifo:v1" xmlns:tns="urn:cz:isvs:iszr:services:IszrAgendaMediaDataCtiAifo:v1" xmlns:e197="urn:cz:isvs:iszr:schemas:IszrAgendaMediaDataCtiAifo:v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" name="IszrAgendaMediaDataCtiAifo" targetNamespace="urn:cz:isvs:iszr:services:IszrAgendaMediaDataCtiAifo:v1">
	<wsdl:documentation>Služba E197 externího rozhraní - Služba umožňuje načítat z AIS agend binární nereferenční údaje, které nejsou uloženy v ROB.</wsdl:documentation>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrAgendaMediaDataCtiAifo:v1" schemaLocation="../xsd/IszrAgendaMediaDataCtiAifo.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrAgendaMediaDataCtiAifo">
		<wsdl:part name="parametry" element="e197:AgendaMediaDataCtiAifo"/>
	</wsdl:message>
	<wsdl:message name="IszrAgendaMediaDataCtiAifoResponse">
		<wsdl:part name="vysledek" element="e197:AgendaMediaDataCtiAifoResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrAgendaMediaDataCtiAifoPortType">
		<wsdl:operation name="IszrAgendaMediaDataCtiAifo">
			<wsdl:input message="tns:IszrAgendaMediaDataCtiAifo"/>
			<wsdl:output message="tns:IszrAgendaMediaDataCtiAifoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrAgendaMediaDataCtiAifoBinding" type="tns:IszrAgendaMediaDataCtiAifoPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrAgendaMediaDataCtiAifo">
			<soap:operation soapAction="IszrAgendaMediaDataCtiAifo"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrAgendaMediaDataCtiAifoService">
		<wsdl:port name="IszrAgendaMediaDataCtiAifoPortService" binding="tns:IszrAgendaMediaDataCtiAifoBinding">
			<soap:address location="IszrAgendaMediaDataCtiAifo"/>
		</wsdl:port>
	</wsdl:service>
	<!-- Vznik 1.0.0, 17.04.2015, Pavel Odstrcil -->
	<!-- Verze 1.10.2, 18.3.2019, ales.teply@autocont.cz, Úprava EopOdpoved, EcdOdpoved: AisAplikacniStatus-NevydanaPolozka -->
	<!-- Verze po revizi 1.10.3, 14.10.2020, Aleš Teplý, RuianCtiProRobDataResponse v1 i v2-->
	<!-- Verze po revizi 1.11.0, 13.8.2021, Aleš Teplý, rozšíření struktury Response ROB v2.0.0, aplikačně zatím omezeno na kompatibilitu s ROB v1.0.9 -->
	<!-- AutoCont CZ a.s. -->
</wsdl:definitions>
