<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVymazRozhodnuti:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVymazRozhodnuti:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVymazRozhodnuti:v1"
	xmlns:e118="urn:cz:isvs:iszr:schemas:IszrRppVymazRozhodnuti:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppVymazRozhodnuti">

	<wsdl:documentation>Služba E118 externího rozhraní - Služba, kterou se zavádí záznamy do Katalogu služeb - RPP služba P15.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 27.02.2012, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- Verze po revizi 1.1.1, 15.10.2021, Aleš Teplý, AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- Verze po revizi 1.2.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVymazRozhodnuti:v1" schemaLocation="../xsd/IszrRppVymazRozhodnuti.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRppVymazRozhodnuti">
		<wsdl:part name="parametry" element="e118:RppVymazRozhodnuti"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVymazRozhodnutiResponse">
		<wsdl:part name="vysledek" element="e118:RppVymazRozhodnutiResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVymazRozhodnutiPortType">
		<wsdl:operation name="IszrRppVymazRozhodnuti">
			<wsdl:input message="IszrRppVymazRozhodnuti"/>
			<wsdl:output message="IszrRppVymazRozhodnutiResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVymazRozhodnutiBinding" type="tns:IszrRppVymazRozhodnutiPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVymazRozhodnuti">
			<soap:operation soapAction="IszrRppVymazRozhodnuti"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVymazRozhodnutiService">
		<wsdl:port name="IszrRppVymazRozhodnutiPortService" binding="tns:IszrRppVymazRozhodnutiBinding">
			<soap:address location="IszrRppVymazRozhodnuti"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
