<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrIsknCtiPrvekKDatuKatastralniUzemi:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrIsknCtiPrvekKDatuKatastralniUzemi:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrIsknCtiPrvekKDatuKatastralniUzemi:v1"
	xmlns:e242d="urn:cz:isvs:iszr:schemas:IszrIsknCtiPrvekKDatuKatastralniUzemi:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrIsknCtiPrvekKDatuKatastralniUzemi">

	<wsdl:documentation>Služba E242d externího rozhraní. Služba která vrátí požadované atributy prvku RUIAN editovaného v ISKN k požadovanému datu. ISKN služba A11, operace ctiKatastralniUzemiKDatu.</wsdl:documentation>

	<!-- Výchozí verze 1.0.0, 2.9.2019 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrIsknCtiPrvekKDatuKatastralniUzemi:v1" schemaLocation="../xsd/IszrIsknCtiPrvekKDatuKatastralniUzemi.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrIsknCtiPrvekKDatuKatastralniUzemi">
		<wsdl:part name="parametry" element="e242d:IsknCtiPrvekKDatuKatastralniUzemi"/>
	</wsdl:message>
	<wsdl:message name="IszrIsknCtiPrvekKDatuKatastralniUzemiResponse">
		<wsdl:part name="vysledek" element="e242d:IsknCtiPrvekKDatuKatastralniUzemiResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrIsknCtiPrvekKDatuKatastralniUzemiPortType">
		<wsdl:operation name="IszrIsknCtiPrvekKDatuKatastralniUzemi">
			<wsdl:input message="IszrIsknCtiPrvekKDatuKatastralniUzemi"/>
			<wsdl:output message="IszrIsknCtiPrvekKDatuKatastralniUzemiResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrIsknCtiPrvekKDatuKatastralniUzemiBinding" type="tns:IszrIsknCtiPrvekKDatuKatastralniUzemiPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrIsknCtiPrvekKDatuKatastralniUzemi">
			<soap:operation soapAction="IszrIsknCtiPrvekKDatuKatastralniUzemi"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrIsknCtiPrvekKDatuKatastralniUzemiService">
		<wsdl:port name="IszrIsknCtiPrvekKDatuKatastralniUzemiPortService" binding="tns:IszrIsknCtiPrvekKDatuKatastralniUzemiBinding">
			<soap:address location="IszrIsknCtiPrvekKDatuKatastralniUzemi"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
