<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVypisProcesniModel:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVypisProcesniModel:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVypisProcesniModel:v1"
	xmlns:e120="urn:cz:isvs:iszr:schemas:IszrRppVypisProcesniModel:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppVypisProcesniModel">

	<wsdl:documentation>Služba E120 externího rozhraní - poskytnutí procesního modelu. Hledá se požadovaný Procesní model, po jeho nalezení se poskytnou veškerá metadata procesního modelu. RPP služba P17.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 14.03.2012, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- Verze po revizi 1.1.1, 15.10.2021, Aleš Teplý, AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- Verze po revizi 1.2.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVypisProcesniModel:v1" schemaLocation="../xsd/IszrRppVypisProcesniModel.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRppVypisProcesniModel">
		<wsdl:part name="parametry" element="e120:RppVypisProcesniModel"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVypisProcesniModelResponse">
		<wsdl:part name="vysledek" element="e120:RppVypisProcesniModelResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVypisProcesniModelPortType">
		<wsdl:operation name="IszrRppVypisProcesniModel">
			<wsdl:input message="tns:IszrRppVypisProcesniModel"/>
			<wsdl:output message="tns:IszrRppVypisProcesniModelResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVypisProcesniModelBinding" type="tns:IszrRppVypisProcesniModelPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVypisProcesniModel">
			<soap:operation soapAction="IszrRppVypisProcesniModel"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVypisProcesniModelService">
		<wsdl:port name="IszrRppVypisProcesniModelPortService" binding="tns:IszrRppVypisProcesniModelBinding">
			<soap:address location="IszrRppVypisProcesniModel"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>