<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekUlice2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekUlice2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekUlice2:v1"
	xmlns:e249q="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekUlice2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianVyhledejPrvekUlice2">

	<wsdl:documentation>Služba E249q externího rozhraní - Vyhledání Ulice z RUIAN. RUIAN služba, operace VyhledejUlice.</wsdl:documentation>
	
	<!-- Výchozí verze 2.0.0, 29.09.2020 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekUlice2:v1" schemaLocation="../xsd/IszrRuianVyhledejPrvekUlice2.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianVyhledejPrvekUlice2">
		<wsdl:part name="parametry" element="e249q:RuianVyhledejPrvekUlice2"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianVyhledejPrvekUlice2Response">
		<wsdl:part name="vysledek" element="e249q:RuianVyhledejPrvekUlice2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianVyhledejPrvekUlice2PortType">
		<wsdl:operation name="IszrRuianVyhledejPrvekUlice2">
			<wsdl:input message="tns:IszrRuianVyhledejPrvekUlice2"/>
			<wsdl:output message="tns:IszrRuianVyhledejPrvekUlice2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianVyhledejPrvekUlice2Binding" type="tns:IszrRuianVyhledejPrvekUlice2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianVyhledejPrvekUlice2">
			<soap:operation soapAction="IszrRuianVyhledejPrvekUlice2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianVyhledejPrvekUlice2Service">
		<wsdl:port name="IszrRuianVyhledejPrvekUlice2PortService" binding="tns:IszrRuianVyhledejPrvekUlice2Binding">
			<soap:address location="IszrRuianVyhledejPrvekUlice2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>