<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekZsj2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekZsj2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekZsj2:v1"
	xmlns:e250s="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekZsj2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiPrvekZsj2">

	<wsdl:documentation>Služba E250s externího rozhraní - Načtení Zsj z RUIAN. RUIAN služba, operace ctiZsj.</wsdl:documentation>

	<!-- Výchozí verze 2.0.0, 6.10.2020 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekZsj2:v1" schemaLocation="../xsd/IszrRuianCtiPrvekZsj2.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianCtiPrvekZsj2">
		<wsdl:part name="parametry" element="e250s:RuianCtiPrvekZsj2"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiPrvekZsj2Response">
		<wsdl:part name="vysledek" element="e250s:RuianCtiPrvekZsj2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiPrvekZsj2PortType">
		<wsdl:operation name="IszrRuianCtiPrvekZsj2">
			<wsdl:input message="tns:IszrRuianCtiPrvekZsj2"/>
			<wsdl:output message="tns:IszrRuianCtiPrvekZsj2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiPrvekZsj2Binding" type="tns:IszrRuianCtiPrvekZsj2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiPrvekZsj2">
			<soap:operation soapAction="IszrRuianCtiPrvekZsj2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiPrvekZsj2Service">
		<wsdl:port name="IszrRuianCtiPrvekZsj2PortService" binding="tns:IszrRuianCtiPrvekZsj2Binding">
			<soap:address location="IszrRuianCtiPrvekZsj2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>