<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekZsj:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekZsj:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekZsj:v1"
	xmlns:e34s="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekZsj:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianVyhledejPrvekZsj">

	<wsdl:documentation>Služba E34s externího rozhraní - Vyhledání zsj z RUIAN. RUIAN služba A03, operace VyhledejZsj.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 22.07.2011, Pavel Kirchner -->
	<!-- Fixovaná verze 1.0.0, 25.10.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekZsj:v1" schemaLocation="../xsd/IszrRuianVyhledejPrvekZsj.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianVyhledejPrvekZsj">
		<wsdl:part name="parametry" element="e34s:RuianVyhledejPrvekZsj"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianVyhledejPrvekZsjResponse">
		<wsdl:part name="vysledek" element="e34s:RuianVyhledejPrvekZsjResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianVyhledejPrvekZsjPortType">
		<wsdl:operation name="IszrRuianVyhledejPrvekZsj">
			<wsdl:input message="tns:IszrRuianVyhledejPrvekZsj"/>
			<wsdl:output message="tns:IszrRuianVyhledejPrvekZsjResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianVyhledejPrvekZsjBinding" type="tns:IszrRuianVyhledejPrvekZsjPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianVyhledejPrvekZsj">
			<soap:operation soapAction="IszrRuianVyhledejPrvekZsj"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianVyhledejPrvekZsjService">
		<wsdl:port name="IszrRuianVyhledejPrvekZsjPortService" binding="tns:IszrRuianVyhledejPrvekZsjBinding">
			<soap:address location="IszrRuianVyhledejPrvekZsj"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>