<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekSpravniObvod2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekSpravniObvod2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekSpravniObvod2:v1"
	xmlns:e250n="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekSpravniObvod2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiPrvekSpravniObvod2">

	<wsdl:documentation>Služba E250n externího rozhraní - Načtení Spravni obvod z RUIAN. RUIAN služba, operace ctiSpravniObvod.</wsdl:documentation>
	
	<!-- Výchozí verze 2.0.0, 6.10.2020 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

  <wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekSpravniObvod2:v1" schemaLocation="../xsd/IszrRuianCtiPrvekSpravniObvod2.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianCtiPrvekSpravniObvod2">
		<wsdl:part name="parametry" element="e250n:RuianCtiPrvekSpravniObvod2"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiPrvekSpravniObvod2Response">
		<wsdl:part name="vysledek" element="e250n:RuianCtiPrvekSpravniObvod2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiPrvekSpravniObvod2PortType">
		<wsdl:operation name="IszrRuianCtiPrvekSpravniObvod2">
			<wsdl:input message="tns:IszrRuianCtiPrvekSpravniObvod2"/>
			<wsdl:output message="tns:IszrRuianCtiPrvekSpravniObvod2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiPrvekSpravniObvod2Binding" type="tns:IszrRuianCtiPrvekSpravniObvod2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiPrvekSpravniObvod2">
			<soap:operation soapAction="IszrRuianCtiPrvekSpravniObvod2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiPrvekSpravniObvod2Service">
		<wsdl:port name="IszrRuianCtiPrvekSpravniObvod2PortService" binding="tns:IszrRuianCtiPrvekSpravniObvod2Binding">
			<soap:address location="IszrRuianCtiPrvekSpravniObvod2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>