<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVlozSla:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVlozSla:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVlozSla:v1"
	xmlns:e142="urn:cz:isvs:iszr:schemas:IszrRppVlozSla:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppVlozSla">

	<wsdl:documentation>Služba E142 externího rozhraní - Služba, kterou se zavádí záznam SLA - RPP služba P39.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 02.02.2012, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- Verze po revizi 1.1.1, 15.10.2021, Aleš Teplý, AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- Verze po revizi 1.2.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVlozSla:v1" schemaLocation="../xsd/IszrRppVlozSla.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRppVlozSla">
		<wsdl:part name="parametry" element="e142:RppVlozSla"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVlozSlaResponse">
		<wsdl:part name="vysledek" element="e142:RppVlozSlaResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVlozSlaPortType">
		<wsdl:operation name="IszrRppVlozSla">
			<wsdl:input message="tns:IszrRppVlozSla"/>
			<wsdl:output message="tns:IszrRppVlozSlaResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVlozSlaBinding" type="tns:IszrRppVlozSlaPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVlozSla">
			<soap:operation soapAction="IszrRppVlozSla"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVlozSlaService">
		<wsdl:port name="IszrRppVlozSlaPortService" binding="tns:IszrRppVlozSlaBinding">
			<soap:address location="IszrRppVlozSla"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>