<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppZpochybniRozhodnuti:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppZpochybniRozhodnuti:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppZpochybniRozhodnuti:v1"
	xmlns:e117="urn:cz:isvs:iszr:schemas:IszrRppZpochybniRozhodnuti:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppZpochybniRozhodnuti">

	<wsdl:documentation>Služba E117 externího rozhraní - Služba na základě předaných dat nastaví příznak "nesprávný" u zpochybněných údajů - RPP služba P14.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 05.01.2012, Aleš Teplý -->
	<!-- Fixovaná verze 1.0.0, 11.01.2012, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppZpochybniRozhodnuti:v1" schemaLocation="../xsd/IszrRppZpochybniRozhodnuti.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRppZpochybniRozhodnuti">
		<wsdl:part name="parametry" element="e117:RppZpochybniRozhodnuti"/>
	</wsdl:message>
	<wsdl:message name="IszrRppZpochybniRozhodnutiResponse">
		<wsdl:part name="vysledek" element="e117:RppZpochybniRozhodnutiResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppZpochybniRozhodnutiPortType">
		<wsdl:operation name="IszrRppZpochybniRozhodnuti">
			<wsdl:input message="tns:IszrRppZpochybniRozhodnuti"/>
			<wsdl:output message="tns:IszrRppZpochybniRozhodnutiResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppZpochybniRozhodnutiBinding" type="tns:IszrRppZpochybniRozhodnutiPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppZpochybniRozhodnuti">
			<soap:operation soapAction="IszrRppZpochybniRozhodnuti"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppZpochybniRozhodnutiService">
		<wsdl:port name="IszrRppZpochybniRozhodnutiPortService" binding="tns:IszrRppZpochybniRozhodnutiBinding">
			<soap:address location="IszrRppZpochybniRozhodnuti"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>