<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekStat2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekStat2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekStat2:v1"
	xmlns:e250o="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekStat2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiPrvekStat2">

	<wsdl:documentation>Služba E250o externího rozhraní - Načtení stát z RUIAN. RUIAN služba, operace ctiStat.</wsdl:documentation>
	
	<!-- Výchozí verze 2.0.0, 6.10.2020 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

  <wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekStat2:v1" schemaLocation="../xsd/IszrRuianCtiPrvekStat2.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianCtiPrvekStat2">
		<wsdl:part name="parametry" element="e250o:RuianCtiPrvekStat2"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiPrvekStat2Response">
		<wsdl:part name="vysledek" element="e250o:RuianCtiPrvekStat2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiPrvekStat2PortType">
		<wsdl:operation name="IszrRuianCtiPrvekStat2">
			<wsdl:input message="tns:IszrRuianCtiPrvekStat2"/>
			<wsdl:output message="tns:IszrRuianCtiPrvekStat2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiPrvekStat2Binding" type="tns:IszrRuianCtiPrvekStat2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiPrvekStat2">
			<soap:operation soapAction="IszrRuianCtiPrvekStat2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiPrvekStat2Service">
		<wsdl:port name="IszrRuianCtiPrvekStat2PortService" binding="tns:IszrRuianCtiPrvekStat2Binding">
			<soap:address location="IszrRuianCtiPrvekStat2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>