<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrAiseoCtiAifo:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrAiseoCtiAifo:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrAiseoCtiAifo:v1"
	xmlns:e159="urn:cz:isvs:iszr:schemas:IszrAiseoCtiAifo:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrAiseoCtiAifo">

	<wsdl:documentation>Služba E159 externího rozhraní - Služba umožňuje načítat z AIS EO nereferenční údaje, které nejsou uloženy v ROB (služba AIS EO X11). Služba vrací údaje pouze tehdy, pokud existuje záznam v ROB.</wsdl:documentation>

	<!-- Vývojová verze 0.1.0, 10.04.2011, Aleš Teplý -->
	<!-- Vývojová verze 0.1.1, 23.04.2012, Aleš Teplý, vracena maximálně jedna osoba -->
	<!-- Vývojová verze 0.2.0, 17.05.2012, Aleš Teplý, dle výchozí IS EO ze 17.5.2012 -->
	<!-- Vývojová verze 0.2.1, 29.05.2012, Aleš Teplý, přejmenování Iseo na Aiseo, dle verze AIS EO z 21.5.2012 -->
	<!-- Vývojová verze 0.2.2, 14.06.2012, Aleš Teplý, dle verze AIS EO z 14.6., úprava OsobaEO, přidáno AiseoSeznamUdaju do interního rozhraní - bez enumerací -->
	<!-- Katalog.7.2 verze 1.1.1, 28.06.2012 Aleš Teplý -->
	<!-- Verze po revizi 1.1.2, 27.07.2012, Aleš Teplý, úprava OsobaEO, vložen elment Osoba -->
	<!-- Katalog.7.3 verze 1.3.0, 29.08.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrAiseoCtiAifo:v1" schemaLocation="../xsd/IszrAiseoCtiAifo.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrAiseoCtiAifo">
		<wsdl:part name="parametry" element="e159:AiseoCtiAifo"/>
	</wsdl:message>
	<wsdl:message name="IszrAiseoCtiAifoResponse">
		<wsdl:part name="vysledek" element="e159:AiseoCtiAifoResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrAiseoCtiAifoPortType">
		<wsdl:operation name="IszrAiseoCtiAifo">
			<wsdl:input message="tns:IszrAiseoCtiAifo"/>
			<wsdl:output message="tns:IszrAiseoCtiAifoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrAiseoCtiAifoBinding" type="tns:IszrAiseoCtiAifoPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrAiseoCtiAifo">
			<soap:operation soapAction="IszrAiseoCtiAifo"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrAiseoCtiAifoService">
		<wsdl:port name="IszrAiseoCtiAifoPortService" binding="tns:IszrAiseoCtiAifoBinding">
			<soap:address location="IszrAiseoCtiAifo"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>