<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrAsyncSmazatFrontu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrAsyncSmazatFrontu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrAsyncSmazatFrontu:v1"
	xmlns:smazf="urn:cz:isvs:iszr:schemas:IszrAsyncSmazatFrontu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrAsyncSmazatFrontu">

	<wsdl:documentation>Služba na smazání obsahu fronty odpovědí asynchronních dotazů.</wsdl:documentation>

	<!-- Vývojová verze 0.0.01, 27.06.2011 Aleš Teplý, vznik rozdělením IszrFronta -->
	<!-- Vývojová verze 0.0.02, 04.08.2011 Aleš Teplý, oprava chybného názvu portType name="IszrAsyncVypisFrontyPortType" -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrAsyncSmazatFrontu:v1" schemaLocation="../xsd/IszrAsyncSmazatFrontu.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrAsyncSmazatFrontu">
		<wsdl:part name="parametry" element="smazf:IszrAsyncSmazatFrontu"/>
	</wsdl:message>
	<wsdl:message name="IszrAsyncSmazatFrontuResponse">
		<wsdl:part name="vysledek" element="smazf:IszrAsyncSmazatFrontuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrAsyncSmazatFrontuPortType">
		<wsdl:operation name="IszrAsyncSmazatFrontu">
			<wsdl:input message="tns:IszrAsyncSmazatFrontu"/>
			<wsdl:output message="tns:IszrAsyncSmazatFrontuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrAsyncSmazatFrontuBinding" type="tns:IszrAsyncSmazatFrontuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrAsyncSmazatFrontu">
			<soap:operation soapAction="IszrAsyncSmazatFrontu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrAsyncSmazatFrontuService">
		<wsdl:port name="IszrAsyncSmazatFrontuPortService" binding="tns:IszrAsyncSmazatFrontuBinding">
			<soap:address location="IszrAsyncSmazatFrontu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>