<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrCtiSouborCiselniku:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrCtiSouborCiselniku:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrCtiSouborCiselniku:v1"
	xmlns:e98="urn:cz:isvs:iszr:schemas:IszrCtiSouborCiselniku:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrCtiSouborCiselniku">

	<wsdl:documentation>Služba vrací odkaz na požadovaný číselník.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 14.10.2011 Pavel Odstrčil, vznik -->
	<!-- Vývojová verze 0.0.2, 26.10.2011 Aleš Teplý, formální úpravy -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrCtiSouborCiselniku:v1" schemaLocation="../xsd/IszrCtiSouborCiselniku.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrCtiSouborCiselniku">
		<wsdl:part name="parametry" element="e98:IszrCtiSouborCiselniku"/>
	</wsdl:message>
	<wsdl:message name="IszrCtiSouborCiselnikuResponse">
		<wsdl:part name="vysledek" element="e98:IszrCtiSouborCiselnikuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrCtiSouborCiselnikuPortType">
		<wsdl:operation name="IszrCtiSouborCiselniku">
			<wsdl:input message="tns:IszrCtiSouborCiselniku"/>
			<wsdl:output message="tns:IszrCtiSouborCiselnikuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrCtiSouborCiselnikuBinding" type="tns:IszrCtiSouborCiselnikuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrCtiSouborCiselniku">
			<soap:operation soapAction="IszrCtiSouborCiselniku"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrCtiSouborCiselnikuService">
		<wsdl:port name="IszrCtiSouborCiselnikuPortService" binding="tns:IszrCtiSouborCiselnikuBinding">
			<soap:address location="IszrCtiSouborCiselniku"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
