<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRosZmenOsobu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRosZmenOsobu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRosZmenOsobu:v1"
	xmlns:e19="urn:cz:isvs:iszr:schemas:IszrRosZmenOsobu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRosZmenOsobu">

	<wsdl:documentation>Služba E19 externího rozhraní - Služba provádí změnu referenčních údajů osoby - služba ROS S04.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 20.06.2011, Aleš Teplý -->
	<!-- Vývojová verze 0.0.2, 14.09.2011, Aleš Teplý, ponechání jen nezbytných namespace -->
	<!-- Fixovaná verze 1.0.0, 18.09.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRosZmenOsobu:v1" schemaLocation="../xsd/IszrRosZmenOsobu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRosZmenOsobu">
		<wsdl:part name="parametry" element="e19:RosZmenOsobu"/>
	</wsdl:message>
	<wsdl:message name="IszrRosZmenOsobuResponse">
		<wsdl:part name="vysledek" element="e19:RosZmenOsobuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRosZmenOsobuPortType">
		<wsdl:operation name="IszrRosZmenOsobu">
			<wsdl:input message="tns:IszrRosZmenOsobu"/>
			<wsdl:output message="tns:IszrRosZmenOsobuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRosZmenOsobuBinding" type="tns:IszrRosZmenOsobuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRosZmenOsobu">
			<soap:operation soapAction="IszrRosZmenOsobu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRosZmenOsobuService">
		<wsdl:port name="IszrRosZmenOsobuPortService" binding="tns:IszrRosZmenOsobuBinding">
			<soap:address location="IszrRosZmenOsobu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>