<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRobVlozObyvatele:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRobVlozObyvatele:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRobVlozObyvatele:v1"
	xmlns:e01="urn:cz:isvs:iszr:schemas:IszrRobVlozObyvatele:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRobVlozObyvatele">

	<wsdl:documentation>Služba E01 externího rozhraní - Služba zakládá nový záznam fyzické osoby v registru - služba ROB E01.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 01.09.2011, Pavel Kirchner -->
	<!-- Vývojová verze 0.0.2, 14.09.2011, Aleš Teplý, ponechání jen nezbytných namespace -->
	<!-- Fixovaná verze 1.0.0, 25.10.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRobVlozObyvatele:v1" schemaLocation="../xsd/IszrRobVlozObyvatele.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRobVlozObyvatele">
		<wsdl:part name="parametry" element="e01:RobVlozObyvatele"/>
	</wsdl:message>
	<wsdl:message name="IszrRobVlozObyvateleResponse">
		<wsdl:part name="vysledek" element="e01:RobVlozObyvateleResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRobVlozObyvatelePortType">
		<wsdl:operation name="IszrRobVlozObyvatele">
			<wsdl:input message="tns:IszrRobVlozObyvatele"/>
			<wsdl:output message="tns:IszrRobVlozObyvateleResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRobVlozObyvateleBinding" type="tns:IszrRobVlozObyvatelePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRobVlozObyvatele">
			<soap:operation soapAction="IszrRobVlozObyvatele"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRobVlozObyvateleService">
		<wsdl:port name="IszrRobVlozObyvatelePortService" binding="tns:IszrRobVlozObyvateleBinding">
			<soap:address location="IszrRobVlozObyvatele"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>