<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekStatKDatu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekStatKDatu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekStatKDatu:v1"
	xmlns:e67o="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekStatKDatu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrIsuiCtiPrvekStatKDatu">

	<wsdl:documentation>Služba E67O externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 10.2.2011, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekStatKDatu:v1" schemaLocation="../xsd/IszrIsuiCtiPrvekStatKDatu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrIsuiCtiPrvekStatKDatu">
		<wsdl:part name="parametry" element="e67o:IsuiCtiPrvekStatKDatu"/>
	</wsdl:message>
	<wsdl:message name="IszrIsuiCtiPrvekStatKDatuResponse">
		<wsdl:part name="vysledek" element="e67o:IsuiCtiPrvekStatKDatuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrIsuiCtiPrvekStatKDatuPortType">
		<wsdl:operation name="IszrIsuiCtiPrvekStatKDatu">
			<wsdl:input message="IszrIsuiCtiPrvekStatKDatu"/>
			<wsdl:output message="IszrIsuiCtiPrvekStatKDatuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrIsuiCtiPrvekStatKDatuBinding" type="tns:IszrIsuiCtiPrvekStatKDatuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrIsuiCtiPrvekStatKDatu">
			<soap:operation soapAction="IszrIsuiCtiPrvekStatKDatu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrIsuiCtiPrvekStatKDatuService">
		<wsdl:port name="IszrIsuiCtiPrvekStatKDatuPortService" binding="tns:IszrIsuiCtiPrvekStatKDatuBinding">
			<soap:address location="IszrIsuiCtiPrvekStatKDatu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
