<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekOrp:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekOrp:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekOrp:v1"
	xmlns:e34j="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekOrp:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianVyhledejPrvekOrp">

	<wsdl:documentation>Služba E34j externího rozhraní - Vyhlednání adresního místa z RUIAN. RUIAN služba A03, operace VyhledejOrp.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 20.07.2011, Aleš Teplý -->
	<!-- Fixovaná verze 1.0.0, 25.10.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekOrp:v1" schemaLocation="../xsd/IszrRuianVyhledejPrvekOrp.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianVyhledejPrvekOrp">
		<wsdl:part name="parametry" element="e34j:RuianVyhledejPrvekOrp"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianVyhledejPrvekOrpResponse">
		<wsdl:part name="vysledek" element="e34j:RuianVyhledejPrvekOrpResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianVyhledejPrvekOrpPortType">
		<wsdl:operation name="IszrRuianVyhledejPrvekOrp">
			<wsdl:input message="tns:IszrRuianVyhledejPrvekOrp"/>
			<wsdl:output message="tns:IszrRuianVyhledejPrvekOrpResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianVyhledejPrvekOrpBinding" type="tns:IszrRuianVyhledejPrvekOrpPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianVyhledejPrvekOrp">
			<soap:operation soapAction="IszrRuianVyhledejPrvekOrp"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianVyhledejPrvekOrpService">
		<wsdl:port name="IszrRuianVyhledejPrvekOrpPortService" binding="tns:IszrRuianVyhledejPrvekOrpBinding">
			<soap:address location="IszrRuianVyhledejPrvekOrp"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>