<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekAdresniMisto2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekAdresniMisto2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekAdresniMisto2:v1"
	xmlns:e249a="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekAdresniMisto2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianVyhledejPrvekAdresniMisto2">

	<wsdl:documentation>Služba E249a externího rozhraní - Vyhledání adresního místa z RUIAN. RUIAN služba, operace VyhledejAdresniMisto.</wsdl:documentation>
	
	<!-- Výchozí verze 2.0.0, 29.09.2020 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekAdresniMisto2:v1" schemaLocation="../xsd/IszrRuianVyhledejPrvekAdresniMisto2.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianVyhledejPrvekAdresniMisto2">
		<wsdl:part name="parametry" element="e249a:RuianVyhledejPrvekAdresniMisto2"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianVyhledejPrvekAdresniMisto2Response">
		<wsdl:part name="vysledek" element="e249a:RuianVyhledejPrvekAdresniMisto2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianVyhledejPrvekAdresniMisto2PortType">
		<wsdl:operation name="IszrRuianVyhledejPrvekAdresniMisto2">
			<wsdl:input message="tns:IszrRuianVyhledejPrvekAdresniMisto2"/>
			<wsdl:output message="tns:IszrRuianVyhledejPrvekAdresniMisto2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianVyhledejPrvekAdresniMisto2Binding" type="tns:IszrRuianVyhledejPrvekAdresniMisto2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianVyhledejPrvekAdresniMisto2">
			<soap:operation soapAction="IszrRuianVyhledejPrvekAdresniMisto2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianVyhledejPrvekAdresniMisto2Service">
		<wsdl:port name="IszrRuianVyhledejPrvekAdresniMisto2PortService" binding="tns:IszrRuianVyhledejPrvekAdresniMisto2Binding">
			<soap:address location="IszrRuianVyhledejPrvekAdresniMisto2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>