<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekPou2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekPou2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekPou2:v1"
	xmlns:e250l="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekPou2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiPrvekPou2">

	<wsdl:documentation>Služba E250l externího rozhraní - Načtení parcely z RUIAN. RUIAN služba, operace CtiPou.</wsdl:documentation>
	
	<!-- Výchozí verze 2.0.0, 6.10.2020 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

  <wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekPou2:v1" schemaLocation="../xsd/IszrRuianCtiPrvekPou2.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianCtiPrvekPou2">
		<wsdl:part name="parametry" element="e250l:RuianCtiPrvekPou2"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiPrvekPou2Response">
		<wsdl:part name="vysledek" element="e250l:RuianCtiPrvekPou2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiPrvekPou2PortType">
		<wsdl:operation name="IszrRuianCtiPrvekPou2">
			<wsdl:input message="tns:IszrRuianCtiPrvekPou2"/>
			<wsdl:output message="tns:IszrRuianCtiPrvekPou2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiPrvekPou2Binding" type="tns:IszrRuianCtiPrvekPou2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiPrvekPou2">
			<soap:operation soapAction="IszrRuianCtiPrvekPou2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiPrvekPou2Service">
		<wsdl:port name="IszrRuianCtiPrvekPou2PortService" binding="tns:IszrRuianCtiPrvekPou2Binding">
			<soap:address location="IszrRuianCtiPrvekPou2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>