<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrOrgPredchudciAifo:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrOrgPredchudciAifo:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrOrgPredchudciAifo:v1"
	xmlns:e76="urn:cz:isvs:iszr:schemas:IszrOrgPredchudciAifo:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrOrgPredchudciAifo">

	<wsdl:documentation>Služba E76 externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 13.02.2012, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrOrgPredchudciAifo:v1" schemaLocation="../xsd/IszrOrgPredchudciAifo.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrOrgPredchudciAifo">
		<wsdl:part name="parametry" element="e76:OrgPredchudciAifo"/>
	</wsdl:message>
	<wsdl:message name="IszrOrgPredchudciAifoResponse">
		<wsdl:part name="vysledek" element="e76:OrgPredchudciAifoResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrOrgPredchudciAifoPortType">
		<wsdl:operation name="IszrOrgPredchudciAifo">
			<wsdl:input message="IszrOrgPredchudciAifo"/>
			<wsdl:output message="IszrOrgPredchudciAifoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrOrgPredchudciAifoBinding" type="tns:IszrOrgPredchudciAifoPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrOrgPredchudciAifo">
			<soap:operation soapAction="IszrOrgPredchudciAifo"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrOrgPredchudciAifoService">
		<wsdl:port name="IIszrOrgPredchudciAifoPortService" binding="tns:IszrOrgPredchudciAifoBinding">
			<soap:address location="IszrOrgPredchudciAifo"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
