<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekMopKDatu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekMopKDatu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekMopKDatu:v1"
	xmlns:e67g="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekMopKDatu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrIsuiCtiPrvekMopKDatu">

	<wsdl:documentation>Služba E67G externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 10.2.2011, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekMopKDatu:v1" schemaLocation="../xsd/IszrIsuiCtiPrvekMopKDatu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrIsuiCtiPrvekMopKDatu">
		<wsdl:part name="parametry" element="e67g:IsuiCtiPrvekMopKDatu"/>
	</wsdl:message>
	<wsdl:message name="IszrIsuiCtiPrvekMopKDatuResponse">
		<wsdl:part name="vysledek" element="e67g:IsuiCtiPrvekMopKDatuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrIsuiCtiPrvekMopKDatuPortType">
		<wsdl:operation name="IszrIsuiCtiPrvekMopKDatu">
			<wsdl:input message="IszrIsuiCtiPrvekMopKDatu"/>
			<wsdl:output message="IszrIsuiCtiPrvekMopKDatuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrIsuiCtiPrvekMopKDatuBinding" type="tns:IszrIsuiCtiPrvekMopKDatuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrIsuiCtiPrvekMopKDatu">
			<soap:operation soapAction="IszrIsuiCtiPrvekMopKDatu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrIsuiCtiPrvekMopKDatuService">
		<wsdl:port name="IszrIsuiCtiPrvekMopKDatuPortService" binding="tns:IszrIsuiCtiPrvekMopKDatuBinding">
			<soap:address location="IszrIsuiCtiPrvekMopKDatu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
