<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRosCtiSeznamIco:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRosCtiSeznamIco:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRosCtiSeznamIco:v1"
	xmlns:e29="urn:cz:isvs:iszr:schemas:IszrRosCtiSeznamIco:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRosCtiSeznamIco">

	<wsdl:documentation>Služba E29 externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 12.10.2011, Jan Sluka -->
	<!-- Fixovaná verze 1.0.0, 30.11.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRosCtiSeznamIco:v1" schemaLocation="../xsd/IszrRosCtiSeznamIco.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRosCtiSeznamIco">
		<wsdl:part name="parametry" element="e29:RosCtiSeznamIco"/>
	</wsdl:message>
	<wsdl:message name="IszrRosCtiSeznamIcoResponse">
		<wsdl:part name="vysledek" element="e29:RosCtiSeznamIcoResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRosCtiSeznamIcoPortType">
		<wsdl:operation name="IszrRosCtiSeznamIco">
			<wsdl:input message="IszrRosCtiSeznamIco"/>
			<wsdl:output message="IszrRosCtiSeznamIcoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRosCtiSeznamIcoBinding" type="tns:IszrRosCtiSeznamIcoPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRosCtiSeznamIco">
			<soap:operation soapAction="IszrRosCtiSeznamIco"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRosCtiSeznamIcoService">
		<wsdl:port name="IszrRosCtiSeznamIcoPortService" binding="tns:IszrRosCtiSeznamIcoBinding">
			<soap:address location="IszrRosCtiSeznamIco"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
