<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVlozSluzbu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVlozSluzbu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVlozSluzbu:v1"
	xmlns:e137="urn:cz:isvs:iszr:schemas:IszrRppVlozSluzbu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppVlozSluzbu">

	<wsdl:documentation>Služba E137 externího rozhraní - Služba, kterou se zavádí záznamy do Katalogu služeb - RPP služba P34.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 21.12.2011, Aleš Teplý -->
	<!-- Fixovaná verze 1.0.0, 11.01.2012, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVlozSluzbu:v1" schemaLocation="../xsd/IszrRppVlozSluzbu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRppVlozSluzbu">
		<wsdl:part name="parametry" element="e137:RppVlozSluzbu"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVlozSluzbuResponse">
		<wsdl:part name="vysledek" element="e137:RppVlozSluzbuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVlozSluzbuPortType">
		<wsdl:operation name="IszrRppVlozSluzbu">
			<wsdl:input message="tns:IszrRppVlozSluzbu"/>
			<wsdl:output message="tns:IszrRppVlozSluzbuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVlozSluzbuBinding" type="tns:IszrRppVlozSluzbuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVlozSluzbu">
			<soap:operation soapAction="IszrRppVlozSluzbu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVlozSluzbuService">
		<wsdl:port name="IszrRppVlozSluzbuPortService" binding="tns:IszrRppVlozSluzbuBinding">
			<soap:address location="IszrRppVlozSluzbu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>