<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekMop:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekMop:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekMop:v1"
	xmlns:e34g="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekMop:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianVyhledejPrvekMop">

	<wsdl:documentation>Služba E34g externího rozhraní - Vyhledání mop z RUIAN. RUIAN služba A03, operace VyhledejMop.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 22.07.2011, Pavel Kirchner -->
	<!-- Fixovaná verze 1.0.0, 25.10.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekMop:v1" schemaLocation="../xsd/IszrRuianVyhledejPrvekMop.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianVyhledejPrvekMop">
		<wsdl:part name="parametry" element="e34g:RuianVyhledejPrvekMop"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianVyhledejPrvekMopResponse">
		<wsdl:part name="vysledek" element="e34g:RuianVyhledejPrvekMopResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianVyhledejPrvekMopPortType">
		<wsdl:operation name="IszrRuianVyhledejPrvekMop">
			<wsdl:input message="tns:IszrRuianVyhledejPrvekMop"/>
			<wsdl:output message="tns:IszrRuianVyhledejPrvekMopResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianVyhledejPrvekMopBinding" type="tns:IszrRuianVyhledejPrvekMopPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianVyhledejPrvekMop">
			<soap:operation soapAction="IszrRuianVyhledejPrvekMop"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianVyhledejPrvekMopService">
		<wsdl:port name="IszrRuianVyhledejPrvekMopPortService" binding="tns:IszrRuianVyhledejPrvekMopBinding">
			<soap:address location="IszrRuianVyhledejPrvekMop"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>