<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRobCtiAifo2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRobCtiAifo2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRobCtiAifo2:v1"
	xmlns:e276="urn:cz:isvs:iszr:schemas:IszrRobCtiAifo2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRobCtiAifo2">

	<wsdl:documentation>Služba E276.</wsdl:documentation>

	<!-- Výchozí verze 1.0.0, 12.08.2021, Aleš Teplý -->
	<!-- Verze po revizi 1.0.1, 15.10.2021, Aleš Teplý, přidává možnou hodnotu u nepovinného elementu Response (RodinnyStavPartnerstviType) -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRobCtiAifo2:v1" schemaLocation="../xsd/IszrRobCtiAifo2.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRobCtiAifo2">
		<wsdl:part name="parametry" element="e276:RobCtiAifo2"/>
	</wsdl:message>
	<wsdl:message name="IszrRobCtiAifo2Response">
		<wsdl:part name="vysledek" element="e276:RobCtiAifo2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRobCtiAifo2PortType">
		<wsdl:operation name="IszrRobCtiAifo2">
			<wsdl:input message="tns:IszrRobCtiAifo2"/>
			<wsdl:output message="tns:IszrRobCtiAifo2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRobCtiAifo2Binding" type="tns:IszrRobCtiAifo2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRobCtiAifo2">
			<soap:operation soapAction="IszrRobCtiAifo2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRobCtiAifo2Service">
		<wsdl:port name="IszrRobCtiAifo2PortService" binding="tns:IszrRobCtiAifo2Binding">
			<soap:address location="IszrRobCtiAifo2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
