<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrCtiSeznamCiselniku:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrCtiSeznamCiselniku:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrCtiSeznamCiselniku:v1"
	xmlns:e97="urn:cz:isvs:iszr:schemas:IszrCtiSeznamCiselniku:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrCtiSeznamCiselniku">

	<wsdl:documentation>Služba vrací seznam číselníků, které je možné získat prostřednictvím ISZR.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 14.10.2011 Pavel Odstrčil, vznik -->
	<!-- Vývojová verze 0.0.2, 26.10.2011 Aleš Teplý, formální úpravy -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrCtiSeznamCiselniku:v1" schemaLocation="../xsd/IszrCtiSeznamCiselniku.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrCtiSeznamCiselniku">
		<wsdl:part name="parametry" element="e97:IszrCtiSeznamCiselniku"/>
	</wsdl:message>
	<wsdl:message name="IszrCtiSeznamCiselnikuResponse">
		<wsdl:part name="vysledek" element="e97:IszrCtiSeznamCiselnikuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrCtiSeznamCiselnikuPortType">
		<wsdl:operation name="IszrCtiSeznamCiselniku">
			<wsdl:input message="tns:IszrCtiSeznamCiselniku"/>
			<wsdl:output message="tns:IszrCtiSeznamCiselnikuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrCtiSeznamCiselnikuBinding" type="tns:IszrCtiSeznamCiselnikuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrCtiSeznamCiselniku">
			<soap:operation soapAction="IszrCtiSeznamCiselniku"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrCtiSeznamCiselnikuService">
		<wsdl:port name="IszrCtiSeznamCiselnikuPortService" binding="tns:IszrCtiSeznamCiselnikuBinding">
			<soap:address location="IszrCtiSeznamCiselniku"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
