<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVypisPusobnostOvm6:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVypisPusobnostOvm6:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVypisPusobnostOvm6:v1"
	xmlns:e297="urn:cz:isvs:iszr:schemas:IszrRppVypisPusobnostOvm6:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppVypisPusobnostOvm6">

	<wsdl:documentation>Služba E297 externího rozhraní - Služba vypíše detailní informace o působnosti OVM v agendě ve struktuře po novele zákona 111/2009 včetně stavu zpochybnění - RPP služba P96.</wsdl:documentation>

	<!-- Výchozí verze 1.0.0, 13.12.2012, Aleš Teplý -->
	<!-- Verze po revizi 1.0.1, 16.3.2022, Aleš Teplý, RPP verze 1.11.5 -->
	<!-- Verze po revizi 1.1.0, 12.4.2022, Aleš Teplý, RPP verze 1.11.8, použití odpovědí registrů v2 -->
	<!-- Verze po revizi 1.2.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVypisPusobnostOvm6:v1" schemaLocation="../xsd/IszrRppVypisPusobnostOvm6.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRppVypisPusobnostOvm6">
		<wsdl:part name="parametry" element="e297:RppVypisPusobnostOvm6"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVypisPusobnostOvm6Response">
		<wsdl:part name="vysledek" element="e297:RppVypisPusobnostOvm6Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVypisPusobnostOvm6PortType">
		<wsdl:operation name="IszrRppVypisPusobnostOvm6">
			<wsdl:input message="IszrRppVypisPusobnostOvm6"/>
			<wsdl:output message="IszrRppVypisPusobnostOvm6Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVypisPusobnostOvm6Binding" type="tns:IszrRppVypisPusobnostOvm6PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVypisPusobnostOvm6">
			<soap:operation soapAction="IszrRppVypisPusobnostOvm6"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVypisPusobnostOvm6Service">
		<wsdl:port name="IszrRppVypisPusobnostOvm6PortService" binding="tns:IszrRppVypisPusobnostOvm6Binding">
			<soap:address location="IszrRppVypisPusobnostOvm6"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
