<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekVusc2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekVusc2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekVusc2:v1"
	xmlns:e249r="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekVusc2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianVyhledejPrvekVusc2">

	<wsdl:documentation>Služba E249r externího rozhraní - Vyhledání Vusc z RUIAN. RUIAN služba, operace VyhledejVusc.</wsdl:documentation>
	
	<!-- Výchozí verze 2.0.0, 29.09.2020 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekVusc2:v1" schemaLocation="../xsd/IszrRuianVyhledejPrvekVusc2.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianVyhledejPrvekVusc2">
		<wsdl:part name="parametry" element="e249r:RuianVyhledejPrvekVusc2"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianVyhledejPrvekVusc2Response">
		<wsdl:part name="vysledek" element="e249r:RuianVyhledejPrvekVusc2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianVyhledejPrvekVusc2PortType">
		<wsdl:operation name="IszrRuianVyhledejPrvekVusc2">
			<wsdl:input message="tns:IszrRuianVyhledejPrvekVusc2"/>
			<wsdl:output message="tns:IszrRuianVyhledejPrvekVusc2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianVyhledejPrvekVusc2Binding" type="tns:IszrRuianVyhledejPrvekVusc2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianVyhledejPrvekVusc2">
			<soap:operation soapAction="IszrRuianVyhledejPrvekVusc2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianVyhledejPrvekVusc2Service">
		<wsdl:port name="IszrRuianVyhledejPrvekVusc2PortService" binding="tns:IszrRuianVyhledejPrvekVusc2Binding">
			<soap:address location="IszrRuianVyhledejPrvekVusc2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>