<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekMomc2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekMomc2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekMomc2:v1"
	xmlns:e250f="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekMomc2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiPrvekMomc2">

	<wsdl:documentation>Služba E250f externího rozhraní - Načtení Momc z RUIAN. RUIAN služba, operace ctiMomc.</wsdl:documentation>
	
	<!-- Výchozí verze 2.0.0, 6.10.2020 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekMomc2:v1" schemaLocation="../xsd/IszrRuianCtiPrvekMomc2.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianCtiPrvekMomc2">
		<wsdl:part name="parametry" element="e250f:RuianCtiPrvekMomc2"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiPrvekMomc2Response">
		<wsdl:part name="vysledek" element="e250f:RuianCtiPrvekMomc2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiPrvekMomc2PortType">
		<wsdl:operation name="IszrRuianCtiPrvekMomc2">
			<wsdl:input message="tns:IszrRuianCtiPrvekMomc2"/>
			<wsdl:output message="tns:IszrRuianCtiPrvekMomc2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiPrvekMomc2Binding" type="tns:IszrRuianCtiPrvekMomc2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiPrvekMomc2">
			<soap:operation soapAction="IszrRuianCtiPrvekMomc2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiPrvekMomc2Service">
		<wsdl:port name="IszrRuianCtiPrvekMomc2PortService" binding="tns:IszrRuianCtiPrvekMomc2Binding">
			<soap:address location="IszrRuianCtiPrvekMomc2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>