<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns="urn:cz:isvs:iszr:services:IszrEcdCtiAifo:v1" xmlns:tns="urn:cz:isvs:iszr:services:IszrEcdCtiAifo:v1" xmlns:e189="urn:cz:isvs:iszr:schemas:IszrEcdCtiAifo:v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" name="IszrEcdCtiAifo" targetNamespace="urn:cz:isvs:iszr:services:IszrEcdCtiAifo:v1">
	<wsdl:documentation>Služba E189 externího rozhraní - Služba umožňuje načítat z ECD nereferenční údaje, které nejsou uloženy v ROB.</wsdl:documentation>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrEcdCtiAifo:v1" schemaLocation="../xsd/IszrEcdCtiAifo.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrEcdCtiAifo">
		<wsdl:part name="parametry" element="e189:EcdCtiAifo"/>
	</wsdl:message>
	<wsdl:message name="IszrEcdCtiAifoResponse">
		<wsdl:part name="vysledek" element="e189:EcdCtiAifoResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrEcdCtiAifoPortType">
		<wsdl:operation name="IszrEcdCtiAifo">
			<wsdl:input message="IszrEcdCtiAifo"/>
			<wsdl:output message="IszrEcdCtiAifoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrEcdCtiAifoBinding" type="tns:IszrEcdCtiAifoPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrEcdCtiAifo">
			<soap:operation soapAction="IszrEcdCtiAifo"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrEcdCtiAifoService">
		<wsdl:port name="IszrEcdCtiAifoPortService" binding="tns:IszrEcdCtiAifoBinding">
			<soap:address location="IszrEcdCtiAifo"/>
		</wsdl:port>
	</wsdl:service>
	<!-- Vznik 1.0.0, 17.04.2015, Pavel Odstrcil -->
	<!-- Verze pro revizi 2.0.0, 13.11.2018, ales.teply@autocont.cz, změna namespace importovaného xsd urn:cz:isvs:ais3:schemas:Ais3EcdCtiAifo:v1 na urn:cz:isvs:aisecd:schemas:AisEcdCtiAifo:v2 a úložiště /ais3 na /aisecd -->
	<!-- Verze 2.0.1, 18.3.2019, ales.teply@autocont.cz, Úprava EcdOdpoved: AisAplikacniStatus-NevydanaPolozka -->
	<!-- Verze po revizi 2.0.2, 14.10.2020, Aleš Teplý, RuianCtiProRobDataResponse v1 i v2-->
	<!-- Verze po revizi 2.1.0, 13.8.2021, Aleš Teplý, rozšíření struktury Response ROB v2.0.0, aplikačně zatím omezeno na kompatibilitu s ROB v1.0.9 -->
	<!-- AutoCont CZ a.s. -->
</wsdl:definitions>
