<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekStat:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekStat:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekStat:v1"
	xmlns:e35o="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekStat:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiPrvekStat">

	<wsdl:documentation>Služba E35o externího rozhraní - Načtení stát z RUIAN. RUIAN služba A04, operace ctiStat.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 28.06.2011, Pavel Kirchner -->
	<!-- Vývojová verze 0.0.2, 26.07.2011, Pavel Kirchner -->
	<!-- Fixovaná verze 1.0.0, 26.10.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

  <wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekStat:v1" schemaLocation="../xsd/IszrRuianCtiPrvekStat.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianCtiPrvekStat">
		<wsdl:part name="parametry" element="e35o:RuianCtiPrvekStat"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiPrvekStatResponse">
		<wsdl:part name="vysledek" element="e35o:RuianCtiPrvekStatResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiPrvekStatPortType">
		<wsdl:operation name="IszrRuianCtiPrvekStat">
			<wsdl:input message="tns:IszrRuianCtiPrvekStat"/>
			<wsdl:output message="tns:IszrRuianCtiPrvekStatResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiPrvekStatBinding" type="tns:IszrRuianCtiPrvekStatPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiPrvekStat">
			<soap:operation soapAction="IszrRuianCtiPrvekStat"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiPrvekStatService">
		<wsdl:port name="IszrRuianCtiPrvekStatPortService" binding="tns:IszrRuianCtiPrvekStatBinding">
			<soap:address location="IszrRuianCtiPrvekStat"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>