<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppZrusAgendu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppZrusAgendu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppZrusAgendu:v1"
	xmlns:e111="urn:cz:isvs:iszr:schemas:IszrRppZrusAgendu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppZrusAgendu">

	<wsdl:documentation>Služba E111 externího rozhraní - Služba ruší (logické zrušení) Agendu v RPP. Nastaví atribut platnost_do na konkrétní datum - RPP služba P08.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 21.12.2011, Aleš Teplý -->
	<!-- Fixovaná verze 1.0.0, 11.01.2012, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppZrusAgendu:v1" schemaLocation="../xsd/IszrRppZrusAgendu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRppZrusAgendu">
		<wsdl:part name="parametry" element="e111:RppZrusAgendu"/>
	</wsdl:message>
	<wsdl:message name="IszrRppZrusAgenduResponse">
		<wsdl:part name="vysledek" element="e111:RppZrusAgenduResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppZrusAgenduPortType">
		<wsdl:operation name="IszrRppZrusAgendu">
			<wsdl:input message="tns:IszrRppZrusAgendu"/>
			<wsdl:output message="tns:IszrRppZrusAgenduResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppZrusAgenduBinding" type="tns:IszrRppZrusAgenduPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppZrusAgendu">
			<soap:operation soapAction="IszrRppZrusAgendu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppZrusAgenduService">
		<wsdl:port name="IszrRppZrusAgenduPortService" binding="tns:IszrRppZrusAgenduBinding">
			<soap:address location="IszrRppZrusAgendu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>