<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRobCtiAifo:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRobCtiAifo:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRobCtiAifo:v1"
	xmlns:e03="urn:cz:isvs:iszr:schemas:IszrRobCtiAifo:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRobCtiAifo">

	<wsdl:documentation>Služba E03.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 20.07.2011, Jan Sluka -->
	<!-- Vývojová verze 0.0.2, 14.09.2011, Aleš Teplý, ponechání jen nezbytných namespace -->
	<!-- Fixovaná verze 1.0.0, 16.09.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRobCtiAifo:v1" schemaLocation="../xsd/IszrRobCtiAifo.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRobCtiAifo">
		<wsdl:part name="parametry" element="e03:RobCtiAifo"/>
	</wsdl:message>
	<wsdl:message name="IszrRobCtiAifoResponse">
		<wsdl:part name="vysledek" element="e03:RobCtiAifoResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRobCtiAifoPortType">
		<wsdl:operation name="IszrRobCtiAifo">
			<wsdl:input message="tns:IszrRobCtiAifo"/>
			<wsdl:output message="tns:IszrRobCtiAifoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRobCtiAifoBinding" type="tns:IszrRobCtiAifoPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRobCtiAifo">
			<soap:operation soapAction="IszrRobCtiAifo"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRobCtiAifoService">
		<wsdl:port name="IszrRobCtiAifoPortService" binding="tns:IszrRobCtiAifoBinding">
			<soap:address location="IszrRobCtiAifo"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
