<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVlozVazbuAgendaSluzba:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVlozVazbuAgendaSluzba:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVlozVazbuAgendaSluzba:v1"
	xmlns:e145="urn:cz:isvs:iszr:schemas:IszrRppVlozVazbuAgendaSluzba:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppVlozVazbuAgendaSluzba">

	<wsdl:documentation>Služba E145 externího rozhraní - Služba na základě předaných dat zapíše nové vazby mezi činností agendy a službou do RPP - RPP služba P42.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 21.12.2011, Aleš Teplý -->
	<!-- Fixovaná verze 1.0.0, 11.01.2012, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVlozVazbuAgendaSluzba:v1" schemaLocation="../xsd/IszrRppVlozVazbuAgendaSluzba.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRppVlozVazbuAgendaSluzba">
		<wsdl:part name="parametry" element="e145:RppVlozVazbuAgendaSluzba"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVlozVazbuAgendaSluzbaResponse">
		<wsdl:part name="vysledek" element="e145:RppVlozVazbuAgendaSluzbaResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVlozVazbuAgendaSluzbaPortType">
		<wsdl:operation name="IszrRppVlozVazbuAgendaSluzba">
			<wsdl:input message="tns:IszrRppVlozVazbuAgendaSluzba"/>
			<wsdl:output message="tns:IszrRppVlozVazbuAgendaSluzbaResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVlozVazbuAgendaSluzbaBinding" type="tns:IszrRppVlozVazbuAgendaSluzbaPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVlozVazbuAgendaSluzba">
			<soap:operation soapAction="IszrRppVlozVazbuAgendaSluzba"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVlozVazbuAgendaSluzbaService">
		<wsdl:port name="IszrRppVlozVazbuAgendaSluzbaPortService" binding="tns:IszrRppVlozVazbuAgendaSluzbaBinding">
			<soap:address location="IszrRppVlozVazbuAgendaSluzba"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>