<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianZmenPrvekIskn:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianZmenPrvekIskn:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianZmenPrvekIskn:v1"
	xmlns:e32="urn:cz:isvs:iszr:schemas:IszrRuianZmenPrvekIskn:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianZmenPrvekIskn">

	<wsdl:documentation>Služba E32 externího rozhraní - Služba pro uložení změn ISKN do RUIAN - RUIAN služba A01.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.01, 15.06.2011, Aleš Teplý -->
	<!-- Vývojová verze 0.0.02, 28.07.2011, Pavel Kirchner -->
	<!-- Vývojová verze 0.0.03, 14.09.2011, Aleš Teplý, CamelCase -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianZmenPrvekIskn:v1" schemaLocation="../xsd/IszrRuianZmenPrvekIskn.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRuianZmenPrvekIskn">
		<wsdl:part name="parametry" element="e32:RuianZmenPrvekIskn"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianZmenPrvekIsknResponse">
		<wsdl:part name="vysledek" element="e32:RuianZmenPrvekIsknResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianZmenPrvekIsknPortType">
		<wsdl:operation name="IszrRuianZmenPrvekIskn">
			<wsdl:input message="tns:IszrRuianZmenPrvekIskn"/>
			<wsdl:output message="tns:IszrRuianZmenPrvekIsknResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianZmenPrvekIsknBinding" type="tns:IszrRuianZmenPrvekIsknPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianZmenPrvekIskn">
			<soap:operation soapAction="IszrRuianZmenPrvekIskn"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianZmenPrvekIsknService">
		<wsdl:port name="IszrRuianZmenPrvekIsknPortService" binding="tns:IszrRuianZmenPrvekIsknBinding">
			<soap:address location="IszrRuianZmenPrvekIskn"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>