<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrOrgKompromitujAis:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrOrgKompromitujAis:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrOrgKompromitujAis:v1"
	xmlns:e73="urn:cz:isvs:iszr:schemas:IszrOrgKompromitujAis:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrOrgKompromitujAis">

	<wsdl:documentation>Služba E73 externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 13.02.2012, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrOrgKompromitujAis:v1" schemaLocation="../xsd/IszrOrgKompromitujAis.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrOrgKompromitujAis">
		<wsdl:part name="parametry" element="e73:OrgKompromitujAis"/>
	</wsdl:message>
	<wsdl:message name="IszrOrgKompromitujAisResponse">
		<wsdl:part name="vysledek" element="e73:OrgKompromitujAisResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrOrgKompromitujAisPortType">
		<wsdl:operation name="IszrOrgKompromitujAis">
			<wsdl:input message="IszrOrgKompromitujAis"/>
			<wsdl:output message="IszrOrgKompromitujAisResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrOrgKompromitujAisBinding" type="tns:IszrOrgKompromitujAisPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrOrgKompromitujAis">
			<soap:operation soapAction="IszrOrgKompromitujAis"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrOrgKompromitujAisService">
		<wsdl:port name="IIszrOrgKompromitujAisPortService" binding="tns:IszrOrgKompromitujAisBinding">
			<soap:address location="IszrOrgKompromitujAis"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
