<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRobVypisBlokace:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRobVypisBlokace:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRobVypisBlokace:v1"
	xmlns:e12="urn:cz:isvs:iszr:schemas:IszrRobVypisBlokace:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRobVypisBlokace">

	<wsdl:documentation>Služba E12.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 12.10.2011, Jan Sluka -->
	<!-- Fixovaná verze 1.0.0, 30.11.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRobVypisBlokace:v1" schemaLocation="../xsd/IszrRobVypisBlokace.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRobVypisBlokace">
		<wsdl:part name="parametry" element="e12:RobVypisBlokace"/>
	</wsdl:message>
	<wsdl:message name="IszrRobVypisBlokaceResponse">
		<wsdl:part name="vysledek" element="e12:RobVypisBlokaceResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRobVypisBlokacePortType">
		<wsdl:operation name="IszrRobVypisBlokace">
			<wsdl:input message="IszrRobVypisBlokace"/>
			<wsdl:output message="IszrRobVypisBlokaceResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRobVypisBlokaceBinding" type="tns:IszrRobVypisBlokacePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRobVypisBlokace">
			<soap:operation soapAction="IszrRobVypisBlokace"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRobVypisBlokaceService">
		<wsdl:port name="IszrRobVypisBlokacePortService" binding="tns:IszrRobVypisBlokaceBinding">
			<soap:address location="IszrRobVypisBlokace"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
