<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrAsyncOdpovedZFronty:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrAsyncOdpovedZFronty:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrAsyncOdpovedZFronty:v1"
	xmlns:odpf="urn:cz:isvs:iszr:schemas:IszrAsyncOdpovedZFronty:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrAsyncOdpovedZFronty">
	<wsdl:documentation>Služba na načtení jednoho výsledku z fronty výsledků asynchronních volání.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.01, 27.06.2011 Aleš Teplý, vznik rozdělením IszrFronta -->
	<!-- Vývojová verze 0.0.02, 04.08.2011 Aleš Teplý, oprava chybného názvu portType name="IszrAsyncVypisFrontyPortType" -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
 	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrAsyncOdpovedZFronty:v1" schemaLocation="../xsd/IszrAsyncOdpovedZFronty.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrAsyncOdpovedZFronty">
		<wsdl:part name="parametry" element="odpf:IszrAsyncOdpovedZFronty"/>
	</wsdl:message>
	<wsdl:message name="IszrAsyncOdpovedZFrontyResponse">
		<wsdl:part name="vysledek" element="odpf:IszrAsyncOdpovedZFrontyResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrAsyncOdpovedZFrontyPortType">
		<wsdl:operation name="IszrAsyncOdpovedZFronty">
			<wsdl:input message="tns:IszrAsyncOdpovedZFronty"/>
			<wsdl:output message="tns:IszrAsyncOdpovedZFrontyResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrAsyncOdpovedZFrontyBinding" type="tns:IszrAsyncOdpovedZFrontyPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrAsyncOdpovedZFronty">
			<soap:operation soapAction="IszrAsyncOdpovedZFronty"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrAsyncOdpovedZFrontyService">
		<wsdl:port name="IszrAsyncOdpovedZFrontyPortService" binding="tns:IszrAsyncOdpovedZFrontyBinding">
			<soap:address location="IszrAsyncOdpovedZFronty"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>