<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrEidentitaCtiProstredkyAifo:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrEidentitaCtiProstredkyAifo:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrEidentitaCtiProstredkyAifo:v1"
	xmlns:e306="urn:cz:isvs:iszr:schemas:IszrEidentitaCtiProstredkyAifo:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrEidentitaCtiProstredkyAifo">

	<wsdl:documentation>Služba E306 externího rozhraní - Služba pro zjištění vlastnictví obecného identifikačního prostředku vedeného v Národním bodu na základě znalosti AIFO.</wsdl:documentation>

	<!-- Vývojová verze 1.0.0, 26.4.2022, Aleš Teplý -->
	<!-- Verze po revizi 1.1.0, 26.5.2022, Aleš Teplý, úprava názvu elementu a typu (sjednocení) -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrEidentitaCtiProstredkyAifo:v1" schemaLocation="../xsd/IszrEidentitaCtiProstredkyAifo.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrEidentitaCtiProstredkyAifo">
		<wsdl:part name="parametry" element="e306:IszrEidentitaCtiProstredkyAifo"/>
	</wsdl:message>
	<wsdl:message name="IszrEidentitaCtiProstredkyAifoResponse">
		<wsdl:part name="vysledek" element="e306:IszrEidentitaCtiProstredkyAifoResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrEidentitaCtiProstredkyAifoPortType">
		<wsdl:operation name="IszrEidentitaCtiProstredkyAifo">
			<wsdl:input message="tns:IszrEidentitaCtiProstredkyAifo"/>
			<wsdl:output message="tns:IszrEidentitaCtiProstredkyAifoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrEidentitaCtiProstredkyAifoBinding" type="tns:IszrEidentitaCtiProstredkyAifoPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrEidentitaCtiProstredkyAifo">
			<soap:operation soapAction="IszrEidentitaCtiProstredkyAifo"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrEidentitaCtiProstredkyAifoService">
		<wsdl:port name="IszrEidentitaCtiProstredkyAifoPortService" binding="tns:IszrEidentitaCtiProstredkyAifoBinding">
			<soap:address location="IszrEidentitaCtiProstredkyAifo"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>