<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRobCtiZmenyZaloz:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRobCtiZmenyZaloz:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRobCtiZmenyZaloz:v1"
	xmlns:e103="urn:cz:isvs:iszr:schemas:IszrRobCtiZmenyZaloz:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRobCtiZmenyZaloz">

	<wsdl:documentation>Služba E103.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 22.11.2011, Aleš Teplý -->
	<!-- Fixovaná verze 1.0.0, 30.11.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRobCtiZmenyZaloz:v1" schemaLocation="../xsd/IszrRobCtiZmenyZaloz.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRobCtiZmenyZaloz">
		<wsdl:part name="parametry" element="e103:RobCtiZmenyZaloz"/>
	</wsdl:message>
	<wsdl:message name="IszrRobCtiZmenyZalozResponse">
		<wsdl:part name="vysledek" element="e103:RobCtiZmenyZalozResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRobCtiZmenyZalozPortType">
		<wsdl:operation name="IszrRobCtiZmenyZaloz">
			<wsdl:input message="tns:IszrRobCtiZmenyZaloz"/>
			<wsdl:output message="tns:IszrRobCtiZmenyZalozResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRobCtiZmenyZalozBinding" type="tns:IszrRobCtiZmenyZalozPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRobCtiZmenyZaloz">
			<soap:operation soapAction="IszrRobCtiZmenyZaloz"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRobCtiZmenyZalozService">
		<wsdl:port name="IszrRobCtiZmenyZalozPortService" binding="tns:IszrRobCtiZmenyZalozBinding">
			<soap:address location="IszrRobCtiZmenyZaloz"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
