<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVypisSeznamPusobnostiOvm3:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVypisSeznamPusobnostiOvm3:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVypisSeznamPusobnostiOvm3:v1"
	xmlns:e298="urn:cz:isvs:iszr:schemas:IszrRppVypisSeznamPusobnostiOvm3:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppVypisSeznamPusobnostiOvm3">

	<wsdl:documentation>Služba E298 externího rozhraní - poskytnutí informací o působnostech definovaných v katalogu působností na základě vstupních parametrů - RPP služba P97.</wsdl:documentation>

	<!-- Výchozí verze 1.0.0, 13.12.2012, Aleš Teplý -->
	<!-- Verze po revizi 1.0.1, 16.3.2022, Aleš Teplý, RPP verze 1.11.5 -->
	<!-- Verze po revizi 1.1.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVypisSeznamPusobnostiOvm3:v1" schemaLocation="../xsd/IszrRppVypisSeznamPusobnostiOvm3.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRppVypisSeznamPusobnostiOvm3">
		<wsdl:part name="parametry" element="e298:RppVypisSeznamPusobnostiOvm3"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVypisSeznamPusobnostiOvm3Response">
		<wsdl:part name="vysledek" element="e298:RppVypisSeznamPusobnostiOvm3Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVypisSeznamPusobnostiOvm3PortType">
		<wsdl:operation name="IszrRppVypisSeznamPusobnostiOvm3">
			<wsdl:input message="IszrRppVypisSeznamPusobnostiOvm3"/>
			<wsdl:output message="IszrRppVypisSeznamPusobnostiOvm3Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVypisSeznamPusobnostiOvm3Binding" type="tns:IszrRppVypisSeznamPusobnostiOvm3PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVypisSeznamPusobnostiOvm3">
			<soap:operation soapAction="IszrRppVypisSeznamPusobnostiOvm3"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVypisSeznamPusobnostiOvm3Service">
		<wsdl:port name="IszrRppVypisSeznamPusobnostiOvm3PortService" binding="tns:IszrRppVypisSeznamPusobnostiOvm3Binding">
			<soap:address location="IszrRppVypisSeznamPusobnostiOvm3"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
