<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns="urn:cz:isvs:iszr:services:IszrRppVypisOpravneniKonzumace:v1" xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVypisOpravneniKonzumace:v1" xmlns:e208="urn:cz:isvs:iszr:schemas:IszrRppVypisOpravneniKonzumace:v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" name="IszrRppVypisOpravneniKonzumace" targetNamespace="urn:cz:isvs:iszr:services:IszrRppVypisOpravneniKonzumace:v1">
	<wsdl:documentation>Služba E208 externího rozhraní - Služba poskytne informace o oprávnění k údajům agendy poskytující údaje pro konkrétní agendu čerpající údaje nebo konkrétní OVM, SPUU čerpající údaje - RPP služba P58.</wsdl:documentation>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVypisOpravneniKonzumace:v1" schemaLocation="../xsd/IszrRppVypisOpravneniKonzumace.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRppVypisOpravneniKonzumace">
		<wsdl:part name="parametry" element="e208:RppVypisOpravneniKonzumace"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVypisOpravneniKonzumaceResponse">
		<wsdl:part name="vysledek" element="e208:RppVypisOpravneniKonzumaceResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVypisOpravneniKonzumacePortType">
		<wsdl:operation name="IszrRppVypisOpravneniKonzumace">
			<wsdl:input message="IszrRppVypisOpravneniKonzumace"/>
			<wsdl:output message="IszrRppVypisOpravneniKonzumaceResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVypisOpravneniKonzumaceBinding" type="tns:IszrRppVypisOpravneniKonzumacePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVypisOpravneniKonzumace">
			<soap:operation soapAction="IszrRppVypisOpravneniKonzumace"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVypisOpravneniKonzumaceService">
		<wsdl:port name="IszrRppVypisOpravneniKonzumacePortService" binding="tns:IszrRppVypisOpravneniKonzumaceBinding">
			<soap:address location="IszrRppVypisOpravneniKonzumace"/>
		</wsdl:port>
	</wsdl:service>

	<!-- Novela zákona 1.0.0, 21.11.2016 Pavel Odstrčil -->
	<!-- Verze po revizi 1.0.1, 15.10.2021, Aleš Teplý, AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- Verze po revizi 1.1.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->

</wsdl:definitions>
