<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrAsyncVypisFronty:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrAsyncVypisFronty:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrAsyncVypisFronty:v1"
	xmlns:vypf="urn:cz:isvs:iszr:schemas:IszrAsyncVypisFronty:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrAsyncVypisFronty">

	<wsdl:documentation>Služba na výpis fronty odpovědí asynchronních dotazů.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 27.06.2011 Aleš Teplý, vznik rozdělením IszrFronta -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrAsyncVypisFronty:v1" schemaLocation="../xsd/IszrAsyncVypisFronty.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrAsyncVypisFronty">
		<wsdl:part name="parametry" element="vypf:IszrAsyncVypisFronty"/>
	</wsdl:message>
	<wsdl:message name="IszrAsyncVypisFrontyResponse">
		<wsdl:part name="vysledek" element="vypf:IszrAsyncVypisFrontyResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrAsyncVypisFrontyPortType">
		<wsdl:operation name="IszrAsyncVypisFronty">
			<wsdl:input message="tns:IszrAsyncVypisFronty"/>
			<wsdl:output message="tns:IszrAsyncVypisFrontyResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrAsyncVypisFrontyBinding" type="tns:IszrAsyncVypisFrontyPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrAsyncVypisFronty">
			<soap:operation soapAction="IszrAsyncVypisFronty"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrAsyncVypisFrontyService">
		<wsdl:port name="IszrAsyncVypisFrontyPortService" binding="tns:IszrAsyncVypisFrontyBinding">
			<soap:address location="IszrAsyncVypisFronty"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>