<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRosCtiIco:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRosCtiIco:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRosCtiIco:v1"
	xmlns:e20="urn:cz:isvs:iszr:schemas:IszrRosCtiIco:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRosCtiIco">

	<wsdl:documentation>Služba E20 externího rozhraní - Služba na základě identifikace osoby pomocí IČO vrací požadované referenční údaje.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 26.07.2011, Aleš Teplý -->
	<!-- Vývojová verze 0.0.2, 14.09.2011, Aleš Teplý, ponechání jen nezbytných namespace -->
	<!-- Fixovaná verze 1.0.0, 18.09.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRosCtiIco:v1" schemaLocation="../xsd/IszrRosCtiIco.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRosCtiIco">
		<wsdl:part name="parametry" element="e20:RosCtiIco"/>
	</wsdl:message>
	<wsdl:message name="IszrRosCtiIcoResponse">
		<wsdl:part name="vysledek" element="e20:RosCtiIcoResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRosCtiIcoPortType">
		<wsdl:operation name="IszrRosCtiIco">
			<wsdl:input message="tns:IszrRosCtiIco"/>
			<wsdl:output message="tns:IszrRosCtiIcoResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRosCtiIcoBinding" type="tns:IszrRosCtiIcoPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRosCtiIco">
			<soap:operation soapAction="IszrRosCtiIco"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRosCtiIcoService">
		<wsdl:port name="IszrRosCtiIcoPortService" binding="tns:IszrRosCtiIcoBinding">
			<soap:address location="IszrRosCtiIco"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>