<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekUlice:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekUlice:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekUlice:v1"
	xmlns:e35q="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekUlice:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiPrvekUlice">

	<wsdl:documentation>Služba E35q externího rozhraní - Načtení ulice z RUIAN. RUIAN služba A04, operace ctiUlice.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 28.06.2011, Pavel Kirchner -->
	<!-- Vývojová verze 0.0.2, 26.07.2011, Pavel Kirchner -->
	<!-- Fixovaná verze 1.0.0, 26.10.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

  <wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekUlice:v1" schemaLocation="../xsd/IszrRuianCtiPrvekUlice.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianCtiPrvekUlice">
		<wsdl:part name="parametry" element="e35q:RuianCtiPrvekUlice"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiPrvekUliceResponse">
		<wsdl:part name="vysledek" element="e35q:RuianCtiPrvekUliceResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiPrvekUlicePortType">
		<wsdl:operation name="IszrRuianCtiPrvekUlice">
			<wsdl:input message="tns:IszrRuianCtiPrvekUlice"/>
			<wsdl:output message="tns:IszrRuianCtiPrvekUliceResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiPrvekUliceBinding" type="tns:IszrRuianCtiPrvekUlicePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiPrvekUlice">
			<soap:operation soapAction="IszrRuianCtiPrvekUlice"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiPrvekUliceService">
		<wsdl:port name="IszrRuianCtiPrvekUlicePortService" binding="tns:IszrRuianCtiPrvekUliceBinding">
			<soap:address location="IszrRuianCtiPrvekUlice"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>