<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrIsuiReklamujPrvek:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrIsuiReklamujPrvek:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrIsuiReklamujPrvek:v1"
	xmlns:e53="urn:cz:isvs:iszr:schemas:IszrIsuiReklamujPrvek:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrIsuiReklamujPrvek">

	<wsdl:documentation>Služba E53 externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 9.2.2011, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- Verze po revizi 1.1.1, 19.03.2012 Aleš Teplý, oprava typů a namespace z ReklamaceCP na Reklamace -->
	<!-- Verze po revizi 1.1.2, 19.5.2022 Aleš Teplý, rozšíření Request -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrIsuiReklamujPrvek:v1" schemaLocation="../xsd/IszrIsuiReklamujPrvek.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrIsuiReklamujPrvek">
		<wsdl:part name="parametry" element="e53:IsuiReklamujPrvek"/>
	</wsdl:message>
	<wsdl:message name="IszrIsuiReklamujPrvekResponse">
		<wsdl:part name="vysledek" element="e53:IsuiReklamujPrvekResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrIsuiReklamujPrvekPortType">
		<wsdl:operation name="IszrIsuiReklamujPrvek">
			<wsdl:input message="IszrIsuiReklamujPrvek"/>
			<wsdl:output message="IszrIsuiReklamujPrvekResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrIsuiReklamujPrvekBinding" type="tns:IszrIsuiReklamujPrvekPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrIsuiReklamujPrvek">
			<soap:operation soapAction="IszrIsuiReklamujPrvek"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrIsuiReklamujPrvekService">
		<wsdl:port name="IszrIsuiReklamujPrvekPortService" binding="tns:IszrIsuiReklamujPrvekBinding">
			<soap:address location="IszrIsuiReklamujPrvek"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
