<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns="urn:cz:isvs:iszr:services:IszrRppZapisDatovouSchranku:v1" xmlns:tns="urn:cz:isvs:iszr:services:IszrRppZapisDatovouSchranku:v1" xmlns:e220="urn:cz:isvs:iszr:schemas:IszrRppZapisDatovouSchranku:v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" name="IszrRppZapisDatovouSchranku" targetNamespace="urn:cz:isvs:iszr:services:IszrRppZapisDatovouSchranku:v1">
	<wsdl:documentation>Služba E220 externího rozhraní - Služba aktualizuje seznam datových schránek k OVM. Službu využívá sekundární editor (ISDS) - RPP služba P56.</wsdl:documentation>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppZapisDatovouSchranku:v1" schemaLocation="../xsd/IszrRppZapisDatovouSchranku.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRppZapisDatovouSchranku">
		<wsdl:part name="parametry" element="e220:RppZapisDatovouSchranku"/>
	</wsdl:message>
	<wsdl:message name="IszrRppZapisDatovouSchrankuResponse">
		<wsdl:part name="vysledek" element="e220:RppZapisDatovouSchrankuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppZapisDatovouSchrankuPortType">
		<wsdl:operation name="IszrRppZapisDatovouSchranku">
			<wsdl:input message="IszrRppZapisDatovouSchranku"/>
			<wsdl:output message="IszrRppZapisDatovouSchrankuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppZapisDatovouSchrankuBinding" type="tns:IszrRppZapisDatovouSchrankuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppZapisDatovouSchranku">
			<soap:operation soapAction="IszrRppZapisDatovouSchranku"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppZapisDatovouSchrankuService">
		<wsdl:port name="IszrRppZapisDatovouSchrankuPortService" binding="tns:IszrRppZapisDatovouSchrankuBinding">
			<soap:address location="IszrRppZapisDatovouSchranku"/>
		</wsdl:port>
	</wsdl:service>

	<!-- Novela zákona 1.0.0, 12.12.2016 Pavel Odstrčil -->
	<!-- Verze po revizi 1.0.1, 15.10.2021, Aleš Teplý, AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- Verze po revizi 1.1.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->

</wsdl:definitions>