<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVypisVyuzitiRocni:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVypisVyuzitiRocni:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVypisVyuzitiRocni:v1"
	xmlns:e161="urn:cz:isvs:iszr:schemas:IszrRppVypisVyuzitiRocni:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppVypisVyuzitiRocni">

	<wsdl:documentation>Služba E161 externího rozhraní - RPP služba P50.</wsdl:documentation>

	<!-- Výchozí verze 0.0.1, 30.05.2012, Aleš Teplý -->
	<!-- Katalog.7.2 verze 1.1.1, 28.06.2012 Aleš Teplý -->
	<!-- Katalog.7.3 verze 1.3.1, 18.10.2012 Aleš Teplý, přidání SeznamIco do Response -->
	<!-- Katalog.7.4 verze 1.4.0, 29.10.2012 Aleš Teplý -->
	<!-- Verze po revizi 1.4.1, 15.10.2021, Aleš Teplý, AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- Verze po revizi 1.5.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVypisVyuzitiRocni:v1" schemaLocation="../xsd/IszrRppVypisVyuzitiRocni.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRppVypisVyuzitiRocni">
		<wsdl:part name="parametry" element="e161:RppVypisVyuzitiRocni"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVypisVyuzitiRocniResponse">
		<wsdl:part name="vysledek" element="e161:RppVypisVyuzitiRocniResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVypisVyuzitiRocniPortType">
		<wsdl:operation name="IszrRppVypisVyuzitiRocni">
			<wsdl:input message="IszrRppVypisVyuzitiRocni"/>
			<wsdl:output message="IszrRppVypisVyuzitiRocniResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVypisVyuzitiRocniBinding" type="tns:IszrRppVypisVyuzitiRocniPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVypisVyuzitiRocni">
			<soap:operation soapAction="IszrRppVypisVyuzitiRocni"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVypisVyuzitiRocniService">
		<wsdl:port name="IszrRppVypisVyuzitiRocniPortService" binding="tns:IszrRppVypisVyuzitiRocniBinding">
			<soap:address location="IszrRppVypisVyuzitiRocni"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
