<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRosVymazProvozovnu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRosVymazProvozovnu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRosVymazProvozovnu:v1"
	xmlns:e27="urn:cz:isvs:iszr:schemas:IszrRosVymazProvozovnu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRosVymazProvozovnu">

	<wsdl:documentation>Služba E27 externího rozhraní - Služba provádí výmaz provozovny z ROS - služba ROS S12.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 28.06.2011, Aleš Teplý -->
	<!-- Vývojová verze 0.0.2, 14.09.2011, Aleš Teplý, ponechání jen nezbytných namespace -->
	<!-- Fixovaná verze 1.0.0, 18.09.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRosVymazProvozovnu:v1" schemaLocation="../xsd/IszrRosVymazProvozovnu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRosVymazProvozovnu">
		<wsdl:part name="parametry" element="e27:RosVymazProvozovnu"/>
	</wsdl:message>
	<wsdl:message name="IszrRosVymazProvozovnuResponse">
		<wsdl:part name="vysledek" element="e27:RosVymazProvozovnuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRosVymazProvozovnuPortType">
		<wsdl:operation name="IszrRosVymazProvozovnu">
			<wsdl:input message="tns:IszrRosVymazProvozovnu"/>
			<wsdl:output message="tns:IszrRosVymazProvozovnuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRosVymazProvozovnuBinding" type="tns:IszrRosVymazProvozovnuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRosVymazProvozovnu">
			<soap:operation soapAction="IszrRosVymazProvozovnu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRosVymazProvozovnuService">
		<wsdl:port name="IszrRosVymazProvozovnuPortService" binding="tns:IszrRosVymazProvozovnuBinding">
			<soap:address location="IszrRosVymazProvozovnu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>