<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekUliceKDatu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekUliceKDatu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekUliceKDatu:v1"
	xmlns:e67q="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekUliceKDatu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrIsuiCtiPrvekUliceKDatu">

	<wsdl:documentation>Služba E67Q externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 10.2.2011, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekUliceKDatu:v1" schemaLocation="../xsd/IszrIsuiCtiPrvekUliceKDatu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrIsuiCtiPrvekUliceKDatu">
		<wsdl:part name="parametry" element="e67q:IsuiCtiPrvekUliceKDatu"/>
	</wsdl:message>
	<wsdl:message name="IszrIsuiCtiPrvekUliceKDatuResponse">
		<wsdl:part name="vysledek" element="e67q:IsuiCtiPrvekUliceKDatuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrIsuiCtiPrvekUliceKDatuPortType">
		<wsdl:operation name="IszrIsuiCtiPrvekUliceKDatu">
			<wsdl:input message="IszrIsuiCtiPrvekUliceKDatu"/>
			<wsdl:output message="IszrIsuiCtiPrvekUliceKDatuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrIsuiCtiPrvekUliceKDatuBinding" type="tns:IszrIsuiCtiPrvekUliceKDatuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrIsuiCtiPrvekUliceKDatu">
			<soap:operation soapAction="IszrIsuiCtiPrvekUliceKDatu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrIsuiCtiPrvekUliceKDatuService">
		<wsdl:port name="IszrIsuiCtiPrvekUliceKDatuPortService" binding="tns:IszrIsuiCtiPrvekUliceKDatuBinding">
			<soap:address location="IszrIsuiCtiPrvekUliceKDatu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
