<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVypisSeznamRozhodnuti:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVypisSeznamRozhodnuti:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVypisSeznamRozhodnuti:v1"
	xmlns:e113="urn:cz:isvs:iszr:schemas:IszrRppVypisSeznamRozhodnuti:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppVypisSeznamRozhodnuti">

	<wsdl:documentation>Služba E113 externího rozhraní - poskytnutí referenčního údaje o rozhodnutích vydaných konkrétním OVM v rámci konkrétní Agendy - RPP služba P10.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 17.10.2011, Aleš Teplý -->
	<!-- Vývojová verze 0.0.2, 20.12.2011, Aleš Teplý, přidán SeznamPrvku, nová verze RPP -->
	<!-- Fixovaná verze 1.0.0, 11.01.2012, Aleš Teplý -->
	<!-- Verze po revizi 1.0.1, 16.02.2012, Aleš Teplý, přejmenování z RppVypisSeznamRozhodnuti na RppVypisSeznamRozhodnuti, přidán SeznamPrvku a OrgStatus -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- Verze po revizi 1.1.1, 15.10.2021, Aleš Teplý, AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- Verze po revizi 1.2.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVypisSeznamRozhodnuti:v1" schemaLocation="../xsd/IszrRppVypisSeznamRozhodnuti.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRppVypisSeznamRozhodnuti">
		<wsdl:part name="parametry" element="e113:RppVypisSeznamRozhodnuti"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVypisSeznamRozhodnutiResponse">
		<wsdl:part name="vysledek" element="e113:RppVypisSeznamRozhodnutiResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVypisSeznamRozhodnutiPortType">
		<wsdl:operation name="IszrRppVypisSeznamRozhodnuti">
			<wsdl:input message="tns:IszrRppVypisSeznamRozhodnuti"/>
			<wsdl:output message="tns:IszrRppVypisSeznamRozhodnutiResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVypisSeznamRozhodnutiBinding" type="tns:IszrRppVypisSeznamRozhodnutiPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVypisSeznamRozhodnuti">
			<soap:operation soapAction="IszrRppVypisSeznamRozhodnuti"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVypisSeznamRozhodnutiService">
		<wsdl:port name="IszrRppVypisSeznamRozhodnutiPortService" binding="tns:IszrRppVypisSeznamRozhodnutiBinding">
			<soap:address location="IszrRppVypisSeznamRozhodnuti"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>