<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekPouKDatu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekPouKDatu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekPouKDatu:v1"
	xmlns:e67l="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekPouKDatu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrIsuiCtiPrvekPouKDatu">

	<wsdl:documentation>Služba E67L externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 10.2.2011, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekPouKDatu:v1" schemaLocation="../xsd/IszrIsuiCtiPrvekPouKDatu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrIsuiCtiPrvekPouKDatu">
		<wsdl:part name="parametry" element="e67l:IsuiCtiPrvekPouKDatu"/>
	</wsdl:message>
	<wsdl:message name="IszrIsuiCtiPrvekPouKDatuResponse">
		<wsdl:part name="vysledek" element="e67l:IsuiCtiPrvekPouKDatuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrIsuiCtiPrvekPouKDatuPortType">
		<wsdl:operation name="IszrIsuiCtiPrvekPouKDatu">
			<wsdl:input message="IszrIsuiCtiPrvekPouKDatu"/>
			<wsdl:output message="IszrIsuiCtiPrvekPouKDatuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrIsuiCtiPrvekPouKDatuBinding" type="tns:IszrIsuiCtiPrvekPouKDatuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrIsuiCtiPrvekPouKDatu">
			<soap:operation soapAction="IszrIsuiCtiPrvekPouKDatu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrIsuiCtiPrvekPouKDatuService">
		<wsdl:port name="IszrIsuiCtiPrvekPouKDatuPortService" binding="tns:IszrIsuiCtiPrvekPouKDatuBinding">
			<soap:address location="IszrIsuiCtiPrvekPouKDatu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
