<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns="urn:cz:isvs:iszr:services:IszrAispVypisDetailIs:v1" xmlns:tns="urn:cz:isvs:iszr:services:IszrAispVypisDetailIs:v1" xmlns:e236="urn:cz:isvs:iszr:schemas:IszrAispVypisDetailIs:v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" name="IszrAispVypisDetailIs" targetNamespace="urn:cz:isvs:iszr:services:IszrAispVypisDetailIs:v1">
	<wsdl:documentation>Služba E236 externího rozhraní - Služba umožňuje načítat z AISP nereferenční údaje o AIS.</wsdl:documentation>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrAispVypisDetailIs:v1" schemaLocation="../xsd/IszrAispVypisDetailIs.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrAispVypisDetailIs">
		<wsdl:part name="parametry" element="e236:AispVypisDetailIs"/>
	</wsdl:message>
	<wsdl:message name="IszrAispVypisDetailIsResponse">
		<wsdl:part name="vysledek" element="e236:AispVypisDetailIsResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrAispVypisDetailIsPortType">
		<wsdl:operation name="IszrAispVypisDetailIs">
			<wsdl:input message="tns:IszrAispVypisDetailIs"/>
			<wsdl:output message="tns:IszrAispVypisDetailIsResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrAispVypisDetailIsBinding" type="tns:IszrAispVypisDetailIsPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrAispVypisDetailIs">
			<soap:operation soapAction="IszrAispVypisDetailIs"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrAispVypisDetailIsService">
		<wsdl:port name="IszrAispVypisDetailIsPortService" binding="tns:IszrAispVypisDetailIsBinding">
			<soap:address location="IszrAispVypisDetailIs"/>
		</wsdl:port>
	</wsdl:service>
	<!-- Vznik 1.0.0, 07.01.2019, Pavel Odstrcil -->
	<!-- AutoCont CZ a.s. -->
</wsdl:definitions>
