<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekMomc:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekMomc:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekMomc:v1"
	xmlns:e35f="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekMomc:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiPrvekMomc">

	<wsdl:documentation>Služba E35f externího rozhraní - Načtení Momc z RUIAN. RUIAN služba A04, operace ctiMomc.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 24.06.2011, Aleš Teplý -->
	<!-- Vývojová verze 0.0.2, 27.07.2011, Pavel Kirchner -->
	<!-- Fixovaná verze 1.0.0, 26.10.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekMomc:v1" schemaLocation="../xsd/IszrRuianCtiPrvekMomc.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianCtiPrvekMomc">
		<wsdl:part name="parametry" element="e35f:RuianCtiPrvekMomc"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiPrvekMomcResponse">
		<wsdl:part name="vysledek" element="e35f:RuianCtiPrvekMomcResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiPrvekMomcPortType">
		<wsdl:operation name="IszrRuianCtiPrvekMomc">
			<wsdl:input message="tns:IszrRuianCtiPrvekMomc"/>
			<wsdl:output message="tns:IszrRuianCtiPrvekMomcResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiPrvekMomcBinding" type="tns:IszrRuianCtiPrvekMomcPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiPrvekMomc">
			<soap:operation soapAction="IszrRuianCtiPrvekMomc"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiPrvekMomcService">
		<wsdl:port name="IszrRuianCtiPrvekMomcPortService" binding="tns:IszrRuianCtiPrvekMomcBinding">
			<soap:address location="IszrRuianCtiPrvekMomc"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>