<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVypisSeznamOvmSpuu2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVypisSeznamOvmSpuu2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVypisSeznamOvmSpuu2:v1"
	xmlns:e304="urn:cz:isvs:iszr:schemas:IszrRppVypisSeznamOvmSpuu2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppVypisSeznamOvmSpuu2">

	<wsdl:documentation>Služba E304 externího rozhraní - Služba vrátí seznam OVM nebo SPUU, které vyhovují výběru podle hodnot zadaných vstupních parametrů - RPP služba P105.</wsdl:documentation>

	<!-- Výchozí verze 1.0.0, 13.12.2012, Aleš Teplý -->
	<!-- Verze po revizi 1.0.1, 16.3.2022, Aleš Teplý, RPP verze 1.11.5 -->
	<!-- Verze po revizi 1.1.0, 12.4.2022, Aleš Teplý, RPP verze 1.11.8, použití odpovědí registrů v2 -->
	<!-- Verze po revizi 1.2.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVypisSeznamOvmSpuu2:v1" schemaLocation="../xsd/IszrRppVypisSeznamOvmSpuu2.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRppVypisSeznamOvmSpuu2">
		<wsdl:part name="parametry" element="e304:RppVypisSeznamOvmSpuu2"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVypisSeznamOvmSpuu2Response">
		<wsdl:part name="vysledek" element="e304:RppVypisSeznamOvmSpuu2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVypisSeznamOvmSpuu2PortType">
		<wsdl:operation name="IszrRppVypisSeznamOvmSpuu2">
			<wsdl:input message="IszrRppVypisSeznamOvmSpuu2"/>
			<wsdl:output message="IszrRppVypisSeznamOvmSpuu2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVypisSeznamOvmSpuu2Binding" type="tns:IszrRppVypisSeznamOvmSpuu2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVypisSeznamOvmSpuu2">
			<soap:operation soapAction="IszrRppVypisSeznamOvmSpuu2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVypisSeznamOvmSpuu2Service">
		<wsdl:port name="IszrRppVypisSeznamOvmSpuu2PortService" binding="tns:IszrRppVypisSeznamOvmSpuu2Binding">
			<soap:address location="IszrRppVypisSeznamOvmSpuu2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
