<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions 
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppZrusPravniPredpis:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppZrusPravniPredpis:v1" 
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppZrusPravniPredpis:v1" 
	xmlns:e128="urn:cz:isvs:iszr:schemas:IszrRppZrusPravniPredpis:v1" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
	name="IszrRppZrusPravniPredpis">
	
	<wsdl:documentation>Služba E128 externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 20.03.2012, Jan Sluka -->
	<!-- Katalog.7.2 verze 1.1.1, 28.06.2012 Aleš Teplý -->
	<!-- Verze po revizi 1.1.2, 15.10.2021, Aleš Teplý, AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- Verze po revizi 1.2.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppZrusPravniPredpis:v1" schemaLocation="../xsd/IszrRppZrusPravniPredpis.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="IszrRppZrusPravniPredpis">
		<wsdl:part name="parametry" element="e128:RppZrusPravniPredpis"/>
	</wsdl:message>
	<wsdl:message name="IszrRppZrusPravniPredpisResponse">
		<wsdl:part name="vysledek" element="e128:RppZrusPravniPredpisResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppZrusPravniPredpisPortType">
		<wsdl:operation name="IszrRppZrusPravniPredpis">
			<wsdl:input message="IszrRppZrusPravniPredpis"/>
			<wsdl:output message="IszrRppZrusPravniPredpisResponse"/>
		</wsdl:operation>
	</wsdl:portType>	
	<wsdl:binding name="IszrRppZrusPravniPredpisBinding" type="tns:IszrRppZrusPravniPredpisPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppZrusPravniPredpis">
			<soap:operation soapAction="IszrRppZrusPravniPredpis"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>	
	<wsdl:service name="IszrRppZrusPravniPredpisService">
		<wsdl:port name="IszrRppZrusPravniPredpisPortService" binding="tns:IszrRppZrusPravniPredpisBinding">
			<soap:address location="IszrRppZrusPravniPredpis"/>
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>
