<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekMomc2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekMomc2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekMomc2:v1"
	xmlns:e249f="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekMomc2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianVyhledejPrvekMomc2">

	<wsdl:documentation>Služba E249f externího rozhraní - Vyhledání momc z RUIAN. RUIAN služba, operace VyhledejMomc.</wsdl:documentation>
	
	<!-- Výchozí verze 2.0.0, 29.09.2020 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekMomc2:v1" schemaLocation="../xsd/IszrRuianVyhledejPrvekMomc2.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianVyhledejPrvekMomc2">
		<wsdl:part name="parametry" element="e249f:RuianVyhledejPrvekMomc2"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianVyhledejPrvekMomc2Response">
		<wsdl:part name="vysledek" element="e249f:RuianVyhledejPrvekMomc2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianVyhledejPrvekMomc2PortType">
		<wsdl:operation name="IszrRuianVyhledejPrvekMomc2">
			<wsdl:input message="tns:IszrRuianVyhledejPrvekMomc2"/>
			<wsdl:output message="tns:IszrRuianVyhledejPrvekMomc2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianVyhledejPrvekMomc2Binding" type="tns:IszrRuianVyhledejPrvekMomc2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianVyhledejPrvekMomc2">
			<soap:operation soapAction="IszrRuianVyhledejPrvekMomc2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianVyhledejPrvekMomc2Service">
		<wsdl:port name="IszrRuianVyhledejPrvekMomc2PortService" binding="tns:IszrRuianVyhledejPrvekMomc2Binding">
			<soap:address location="IszrRuianVyhledejPrvekMomc2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>