<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVypisAgendu5:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVypisAgendu5:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVypisAgendu5:v1"
	xmlns:e260="urn:cz:isvs:iszr:schemas:IszrRppVypisAgendu5:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:ns="http://www.w3.org/2004/08/xop/include"
	xmlns:ns1="urn:cz:isvs:iszr:schemas:IszrAbstract:v1"
	xmlns:ns2="urn:cz:isvs:reg:schemas:RegTypy:v1"
	xmlns:ns3="urn:cz:isvs:rpp:schemas:RppDotazyData:v1"
	xmlns:ns4="urn:cz:isvs:rpp:schemas:RppDotazyTypy:v1"
	xmlns:ns5="urn:cz:isvs:rpp:schemas:RppEditaceTypy:v1"
	xmlns:ns6="urn:cz:isvs:rpp:schemas:RppTypy:v1"
	name="IszrRppVypisAgendu5">

	<wsdl:documentation>Služba E260 externího rozhraní - Služba vypíše detailní informace o agendě ve struktuře po novele zákona 111/2009 - RPP služba P82.</wsdl:documentation>

	<!-- Vytvoření nové verze služby pro výpis údajů agendy, RPP 1.10.1, 12.10.2020, Aleš Teplý -->
	<!-- Verze po revizi 1.10.2, 15.10.2021, Aleš Teplý, AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- Verze po revizi 1.11.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVypisAgendu5:v1" schemaLocation="../xsd/IszrRppVypisAgendu5.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRppVypisAgendu5">
		<wsdl:part name="parametry" element="e260:RppVypisAgendu5"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVypisAgendu5Response">
		<wsdl:part name="vysledek" element="e260:RppVypisAgendu5Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVypisAgendu5PortType">
		<wsdl:operation name="IszrRppVypisAgendu5">
			<wsdl:input message="IszrRppVypisAgendu5"/>
			<wsdl:output message="IszrRppVypisAgendu5Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVypisAgendu5Binding" type="tns:IszrRppVypisAgendu5PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVypisAgendu5">
			<soap:operation soapAction="IszrRppVypisAgendu5"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVypisAgendu5Service">
		<wsdl:port name="IszrRppVypisAgendu5PortService" binding="tns:IszrRppVypisAgendu5Binding">
			<soap:address location="IszrRppVypisAgendu5"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
