<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrOrgZrusAis:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrOrgZrusAis:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrOrgZrusAis:v1"
	xmlns:e81="urn:cz:isvs:iszr:schemas:IszrOrgZrusAis:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrOrgZrusAis">

	<wsdl:documentation>Služba E81 externího rozhraní.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 31.07.2011, Jan Sluka -->
	<!-- Vývojová verze 0.0.2, 12.08.2011, Jan Sluka, CaseSensitive upravy -->
	<!-- Vývojová verze 0.0.3, 07.09.2011, Aleš Teplý, CaseSensitive upravy -->
	<!-- Vývojová verze 0.0.4, 14.09.2011, Aleš Teplý, ponechání jen nezbytných namespace -->
	<!-- Vývojová verze 0.0.5, 11.11.2011, Aleš Teplý, oprava "name" -->
	<!-- Fixovaná verze 1.0.0, 30.11.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrOrgZrusAis:v1" schemaLocation="../xsd/IszrOrgZrusAis.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrOrgZrusAis">
		<wsdl:part name="parametry" element="e81:OrgZrusAis"/>
	</wsdl:message>
	<wsdl:message name="IszrOrgZrusAisResponse">
		<wsdl:part name="vysledek" element="e81:OrgZrusAisResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrOrgZrusAisPortType">
		<wsdl:operation name="IszrOrgZrusAis">
			<wsdl:input message="tns:IszrOrgZrusAis"/>
			<wsdl:output message="tns:IszrOrgZrusAisResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrOrgZrusAisBinding" type="tns:IszrOrgZrusAisPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrOrgZrusAis">
			<soap:operation soapAction="IszrOrgZrusAis"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrOrgZrusAisService">
		<wsdl:port name="IIszrOrgZrusAisPortService" binding="tns:IszrOrgZrusAisBinding">
			<soap:address location="IszrOrgZrusAis"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
