<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRobCtiEditora:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRobCtiEditora:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRobCtiEditora:v1"
	xmlns:e15="urn:cz:isvs:iszr:schemas:IszrRobCtiEditora:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRobCtiEditora">

	<wsdl:documentation>Služba E15.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 12.10.2011, Jan Sluka -->
	<!-- Fixovaná verze 1.0.0, 30.11.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRobCtiEditora:v1" schemaLocation="../xsd/IszrRobCtiEditora.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRobCtiEditora">
		<wsdl:part name="parametry" element="e15:RobCtiEditora"/>
	</wsdl:message>
	<wsdl:message name="IszrRobCtiEditoraResponse">
		<wsdl:part name="vysledek" element="e15:RobCtiEditoraResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRobCtiEditoraPortType">
		<wsdl:operation name="IszrRobCtiEditora">
			<wsdl:input message="IszrRobCtiEditora"/>
			<wsdl:output message="IszrRobCtiEditoraResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRobCtiEditoraBinding" type="tns:IszrRobCtiEditoraPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRobCtiEditora">
			<soap:operation soapAction="IszrRobCtiEditora"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRobCtiEditoraService">
		<wsdl:port name="IszrRobCtiEditoraPortService" binding="tns:IszrRobCtiEditoraBinding">
			<soap:address location="IszrRobCtiEditora"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
