<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekKatastralniUzemi:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekKatastralniUzemi:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekKatastralniUzemi:v1"
	xmlns:e35d="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekKatastralniUzemi:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiPrvekKatastralniUzemi">

	<wsdl:documentation>Služba E35d externího rozhraní - Načtení katastrálního území z RUIAN. RUIAN služba A04, operace ctiKatastralniUzemi.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 24.06.2011, Aleš Teplý -->
	<!-- Vývojová verze 0.0.2, 27.07.2011, Pavel Kirchner -->
	<!-- Fixovaná verze 1.0.0, 26.10.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekKatastralniUzemi:v1" schemaLocation="../xsd/IszrRuianCtiPrvekKatastralniUzemi.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianCtiPrvekKatastralniUzemi">
		<wsdl:part name="parametry" element="e35d:RuianCtiPrvekKatastralniUzemi"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiPrvekKatastralniUzemiResponse">
		<wsdl:part name="vysledek" element="e35d:RuianCtiPrvekKatastralniUzemiResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiPrvekKatastralniUzemiPortType">
		<wsdl:operation name="IszrRuianCtiPrvekKatastralniUzemi">
			<wsdl:input message="tns:IszrRuianCtiPrvekKatastralniUzemi"/>
			<wsdl:output message="tns:IszrRuianCtiPrvekKatastralniUzemiResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiPrvekKatastralniUzemiBinding" type="tns:IszrRuianCtiPrvekKatastralniUzemiPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiPrvekKatastralniUzemi">
			<soap:operation soapAction="IszrRuianCtiPrvekKatastralniUzemi"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiPrvekKatastralniUzemiService">
		<wsdl:port name="IszrRuianCtiPrvekKatastralniUzemiPortService" binding="tns:IszrRuianCtiPrvekKatastralniUzemiBinding">
			<soap:address location="IszrRuianCtiPrvekKatastralniUzemi"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>