<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions 
	targetNamespace="urn:cz:isvs:iszr:services:IszrIsknCtiVlastniky:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrIsknCtiVlastniky:v1" 
	xmlns:tns="urn:cz:isvs:iszr:services:IszrIsknCtiVlastniky:v1" 
	xmlns:e41="urn:cz:isvs:iszr:schemas:IszrIsknCtiVlastniky:v1" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
	name="IszrIsknCtiVlastniky">

	<wsdl:documentation>Služba E41 externího rozhraní.</wsdl:documentation>
	<!-- Vývojová verze 0.0.1, 23.03.2012, Jan Sluka -->
	<!-- Katalog.7.2 verze 1.1.1, 28.06.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrIsknCtiVlastniky:v1" schemaLocation="../xsd/IszrIsknCtiVlastniky.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrIsknCtiVlastniky">
		<wsdl:part name="parametry" element="e41:IsknCtiVlastniky"/>
	</wsdl:message>
	<wsdl:message name="IszrIsknCtiVlastnikyResponse">
		<wsdl:part name="vysledek" element="e41:IsknCtiVlastnikyResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrIsknCtiVlastnikyPortType">
		<wsdl:operation name="IszrIsknCtiVlastniky">
			<wsdl:input message="IszrIsknCtiVlastniky"/>
			<wsdl:output message="IszrIsknCtiVlastnikyResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrIsknCtiVlastnikyBinding" type="tns:IszrIsknCtiVlastnikyPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrIsknCtiVlastniky">
			<soap:operation soapAction="IszrIsknCtiVlastniky"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrIsknCtiVlastnikyService">
		<wsdl:port name="IszrIsknCtiVlastnikyPortService" binding="tns:IszrIsknCtiVlastnikyBinding">
			<soap:address location="IszrIsknCtiVlastniky"/>
		</wsdl:port>
	</wsdl:service>	

</wsdl:definitions>
