<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianSouboryDat:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianSouboryDat:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianSouboryDat:v1"
	xmlns:e40="urn:cz:isvs:iszr:schemas:IszrRuianSouboryDat:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianSouboryDat">

	<wsdl:documentation>Služba E40 externího rozhraní. Služba pro poskytnutí odkazů na soubory s kompletními daty RUIAN. RUIAN služba A26.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 9.2.2011, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- Verze po revizi 1.4.3, 16.04.2013, Aleš Teplý, změna Request: TypVymennehoFormatu - zrušeny některé typy (např. ST_ZKHG, ST_ZKHH, ST_ZKHO...) -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianSouboryDat:v1" schemaLocation="../xsd/IszrRuianSouboryDat.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRuianSouboryDat">
		<wsdl:part name="parametry" element="e40:RuianSouboryDat"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianSouboryDatResponse">
		<wsdl:part name="vysledek" element="e40:RuianSouboryDatResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianSouboryDatPortType">
		<wsdl:operation name="IszrRuianSouboryDat">
			<wsdl:input message="IszrRuianSouboryDat"/>
			<wsdl:output message="IszrRuianSouboryDatResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianSouboryDatBinding" type="tns:IszrRuianSouboryDatPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianSouboryDat">
			<soap:operation soapAction="IszrRuianSouboryDat"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianSouboryDatService">
		<wsdl:port name="IszrRuianSouboryDatPortService" binding="tns:IszrRuianSouboryDatBinding">
			<soap:address location="IszrRuianSouboryDat"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
