<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRppVypisSeznamAisAgenda:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRppVypisSeznamAisAgenda:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRppVypisSeznamAisAgenda:v1"
	xmlns:e303="urn:cz:isvs:iszr:schemas:IszrRppVypisSeznamAisAgenda:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRppVypisSeznamAisAgenda">

	<wsdl:documentation>Služba E303 externího rozhraní - RPP služba P104.</wsdl:documentation>

	<!-- Výchozí verze 1.0.0, 13.12.2012, Aleš Teplý -->
	<!-- Verze po revizi 1.1.0, 25.5.2022, Aleš Teplý, Response - AplikacniStatus - VysledekSubKod - upraveno a rozšířeno enumeration -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRppVypisSeznamAisAgenda:v1" schemaLocation="../xsd/IszrRppVypisSeznamAisAgenda.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRppVypisSeznamAisAgenda">
		<wsdl:part name="parametry" element="e303:RppVypisSeznamAisAgenda"/>
	</wsdl:message>
	<wsdl:message name="IszrRppVypisSeznamAisAgendaResponse">
		<wsdl:part name="vysledek" element="e303:RppVypisSeznamAisAgendaResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRppVypisSeznamAisAgendaPortType">
		<wsdl:operation name="IszrRppVypisSeznamAisAgenda">
			<wsdl:input message="IszrRppVypisSeznamAisAgenda"/>
			<wsdl:output message="IszrRppVypisSeznamAisAgendaResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRppVypisSeznamAisAgendaBinding" type="tns:IszrRppVypisSeznamAisAgendaPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRppVypisSeznamAisAgenda">
			<soap:operation soapAction="IszrRppVypisSeznamAisAgenda"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRppVypisSeznamAisAgendaService">
		<wsdl:port name="IszrRppVypisSeznamAisAgendaPortService" binding="tns:IszrRppVypisSeznamAisAgendaBinding">
			<soap:address location="IszrRppVypisSeznamAisAgenda"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
