<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekOkres2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekOkres2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianVyhledejPrvekOkres2:v1"
	xmlns:e249i="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekOkres2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianVyhledejPrvekOkres2">

	<wsdl:documentation>Služba E249i externího rozhraní - Vyhledání okresu z RUIAN. RUIAN služba, operace VyhledejOkres.</wsdl:documentation>
	
	<!-- Výchozí verze 2.0.0, 29.09.2020 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianVyhledejPrvekOkres2:v1" schemaLocation="../xsd/IszrRuianVyhledejPrvekOkres2.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianVyhledejPrvekOkres2">
		<wsdl:part name="parametry" element="e249i:RuianVyhledejPrvekOkres2"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianVyhledejPrvekOkres2Response">
		<wsdl:part name="vysledek" element="e249i:RuianVyhledejPrvekOkres2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianVyhledejPrvekOkres2PortType">
		<wsdl:operation name="IszrRuianVyhledejPrvekOkres2">
			<wsdl:input message="tns:IszrRuianVyhledejPrvekOkres2"/>
			<wsdl:output message="tns:IszrRuianVyhledejPrvekOkres2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianVyhledejPrvekOkres2Binding" type="tns:IszrRuianVyhledejPrvekOkres2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianVyhledejPrvekOkres2">
			<soap:operation soapAction="IszrRuianVyhledejPrvekOkres2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianVyhledejPrvekOkres2Service">
		<wsdl:port name="IszrRuianVyhledejPrvekOkres2PortService" binding="tns:IszrRuianVyhledejPrvekOkres2Binding">
			<soap:address location="IszrRuianVyhledejPrvekOkres2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>