<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekKrajKDatu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekKrajKDatu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekKrajKDatu:v1"
	xmlns:e67e="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekKrajKDatu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrIsuiCtiPrvekKrajKDatu">

	<wsdl:documentation>Služba E67E externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 10.2.2011, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekKrajKDatu:v1" schemaLocation="../xsd/IszrIsuiCtiPrvekKrajKDatu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrIsuiCtiPrvekKrajKDatu">
		<wsdl:part name="parametry" element="e67e:IsuiCtiPrvekKrajKDatu"/>
	</wsdl:message>
	<wsdl:message name="IszrIsuiCtiPrvekKrajKDatuResponse">
		<wsdl:part name="vysledek" element="e67e:IsuiCtiPrvekKrajKDatuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrIsuiCtiPrvekKrajKDatuPortType">
		<wsdl:operation name="IszrIsuiCtiPrvekKrajKDatu">
			<wsdl:input message="IszrIsuiCtiPrvekKrajKDatu"/>
			<wsdl:output message="IszrIsuiCtiPrvekKrajKDatuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrIsuiCtiPrvekKrajKDatuBinding" type="tns:IszrIsuiCtiPrvekKrajKDatuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrIsuiCtiPrvekKrajKDatu">
			<soap:operation soapAction="IszrIsuiCtiPrvekKrajKDatu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrIsuiCtiPrvekKrajKDatuService">
		<wsdl:port name="IszrIsuiCtiPrvekKrajKDatuPortService" binding="tns:IszrIsuiCtiPrvekKrajKDatuBinding">
			<soap:address location="IszrIsuiCtiPrvekKrajKDatu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
