<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekOrpKDatu2:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekOrpKDatu2:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekOrpKDatu2:v1"
	xmlns:e252j="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekOrpKDatu2:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrIsuiCtiPrvekOrpKDatu2">

	<wsdl:documentation>Služba E252J externího rozhraní.</wsdl:documentation>

	<!-- Výchozí verze 2.0.0, 14.10.2020 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekOrpKDatu2:v1" schemaLocation="../xsd/IszrIsuiCtiPrvekOrpKDatu2.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrIsuiCtiPrvekOrpKDatu2">
		<wsdl:part name="parametry" element="e252j:IsuiCtiPrvekOrpKDatu2"/>
	</wsdl:message>
	<wsdl:message name="IszrIsuiCtiPrvekOrpKDatu2Response">
		<wsdl:part name="vysledek" element="e252j:IsuiCtiPrvekOrpKDatu2Response"/>
	</wsdl:message>
	<wsdl:portType name="IszrIsuiCtiPrvekOrpKDatu2PortType">
		<wsdl:operation name="IszrIsuiCtiPrvekOrpKDatu2">
			<wsdl:input message="IszrIsuiCtiPrvekOrpKDatu2"/>
			<wsdl:output message="IszrIsuiCtiPrvekOrpKDatu2Response"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrIsuiCtiPrvekOrpKDatu2Binding" type="tns:IszrIsuiCtiPrvekOrpKDatu2PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrIsuiCtiPrvekOrpKDatu2">
			<soap:operation soapAction="IszrIsuiCtiPrvekOrpKDatu2"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrIsuiCtiPrvekOrpKDatu2Service">
		<wsdl:port name="IszrIsuiCtiPrvekOrpKDatu2PortService" binding="tns:IszrIsuiCtiPrvekOrpKDatu2Binding">
			<soap:address location="IszrIsuiCtiPrvekOrpKDatu2"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
