<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRosCtiZmeny:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRosCtiZmeny:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRosCtiZmeny:v1"
	xmlns:e28="urn:cz:isvs:iszr:schemas:IszrRosCtiZmeny:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRosCtiZmeny">

	<wsdl:documentation>Služba E28 externího rozhraní - Vydání seznamu IČO, u kterých došlo ke změně referenčních údajů - služba ROS S13.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 02.07.2011, Jan Sluka -->
	<!-- Vývojová verze 0.0.2, 14.09.2011, Aleš Teplý, ponechání jen nezbytných namespace -->
	<!-- Fixovaná verze 1.0.0, 22.09.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRosCtiZmeny:v1" schemaLocation="../xsd/IszrRosCtiZmeny.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRosCtiZmeny">
		<wsdl:part name="parametry" element="e28:RosCtiZmeny"/>
	</wsdl:message>
	<wsdl:message name="IszrRosCtiZmenyResponse">
		<wsdl:part name="vysledek" element="e28:RosCtiZmenyResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRosCtiZmenyPortType">
		<wsdl:operation name="IszrRosCtiZmeny">
			<wsdl:input message="IszrRosCtiZmeny"/>
			<wsdl:output message="IszrRosCtiZmenyResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRosCtiZmenyBinding" type="tns:IszrRosCtiZmenyPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRosCtiZmeny">
			<soap:operation soapAction="IszrRosCtiZmeny"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRosCtiZmenyService">
		<wsdl:port name="IszrRosCtiZmenyPortService" binding="tns:IszrRosCtiZmenyBinding">
			<soap:address location="IszrRosCtiZmeny"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
