<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrAsyncPushOdpovedZFronty:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrAsyncPushOdpovedZFronty:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrAsyncPushOdpovedZFronty:v1"
	xmlns:podp="urn:cz:isvs:iszr:schemas:IszrAsyncPushOdpovedZFronty:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrAsyncPushOdpovedZFronty">
	<wsdl:documentation>Aktivní zaslání (PUSH) jednoho výsledku z fronty výsledků asynchronních volání. Definice rozhraní pro službu běžící na straně AIS, služba je volána ISZR.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.01, 12.10.2011 Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrAsyncPushOdpovedZFronty:v1" schemaLocation="../xsd/IszrAsyncPushOdpovedZFronty.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrAsyncPushOdpovedZFronty">
		<wsdl:part name="parametry" element="podp:IszrAsyncPushOdpovedZFronty"/>
	</wsdl:message>
	<wsdl:message name="IszrAsyncPushOdpovedZFrontyResponse">
		<wsdl:part name="vysledek" element="podp:IszrAsyncPushOdpovedZFrontyResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrAsyncPushOdpovedZFrontyPortType">
		<wsdl:operation name="IszrAsyncPushOdpovedZFronty">
			<wsdl:input message="tns:IszrAsyncPushOdpovedZFronty"/>
			<wsdl:output message="tns:IszrAsyncPushOdpovedZFrontyResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrAsyncPushOdpovedZFrontyBinding" type="tns:IszrAsyncPushOdpovedZFrontyPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrAsyncPushOdpovedZFronty">
			<soap:operation soapAction="IszrAsyncPushOdpovedZFronty"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrAsyncPushOdpovedZFrontyService">
		<wsdl:port name="IszrAsyncPushOdpovedZFrontyPortService" binding="tns:IszrAsyncPushOdpovedZFrontyBinding">
			<soap:address location="IszrAsyncPushOdpovedZFronty"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>