<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekVusc:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekVusc:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiPrvekVusc:v1"
	xmlns:e35r="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekVusc:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiPrvekVusc">

	<wsdl:documentation>Služba E35r externího rozhraní - Načtení vusc z RUIAN. RUIAN služba A04, operace ctiVusc.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 28.06.2011, Pavel Kirchner -->
	<!-- Vývojová verze 0.0.2, 26.07.2011, Pavel Kirchner -->
	<!-- Fixovaná verze 1.0.0, 26.10.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

  <wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiPrvekVusc:v1" schemaLocation="../xsd/IszrRuianCtiPrvekVusc.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IszrRuianCtiPrvekVusc">
		<wsdl:part name="parametry" element="e35r:RuianCtiPrvekVusc"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiPrvekVuscResponse">
		<wsdl:part name="vysledek" element="e35r:RuianCtiPrvekVuscResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiPrvekVuscPortType">
		<wsdl:operation name="IszrRuianCtiPrvekVusc">
			<wsdl:input message="tns:IszrRuianCtiPrvekVusc"/>
			<wsdl:output message="tns:IszrRuianCtiPrvekVuscResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiPrvekVuscBinding" type="tns:IszrRuianCtiPrvekVuscPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiPrvekVusc">
			<soap:operation soapAction="IszrRuianCtiPrvekVusc"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiPrvekVuscService">
		<wsdl:port name="IszrRuianCtiPrvekVuscPortService" binding="tns:IszrRuianCtiPrvekVuscBinding">
			<soap:address location="IszrRuianCtiPrvekVusc"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>