<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekSpravniObvodKDatu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekSpravniObvodKDatu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrIsuiCtiPrvekSpravniObvodKDatu:v1"
	xmlns:e67n="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekSpravniObvodKDatu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrIsuiCtiPrvekSpravniObvodKDatu">

	<wsdl:documentation>Služba E67N externího rozhraní.</wsdl:documentation>

	<!-- Vývojová verze 0.0.1, 10.2.2011, Jan Sluka -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrIsuiCtiPrvekSpravniObvodKDatu:v1" schemaLocation="../xsd/IszrIsuiCtiPrvekSpravniObvodKDatu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrIsuiCtiPrvekSpravniObvodKDatu">
		<wsdl:part name="parametry" element="e67n:IsuiCtiPrvekSpravniObvodKDatu"/>
	</wsdl:message>
	<wsdl:message name="IszrIsuiCtiPrvekSpravniObvodKDatuResponse">
		<wsdl:part name="vysledek" element="e67n:IsuiCtiPrvekSpravniObvodKDatuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrIsuiCtiPrvekSpravniObvodKDatuPortType">
		<wsdl:operation name="IszrIsuiCtiPrvekSpravniObvodKDatu">
			<wsdl:input message="IszrIsuiCtiPrvekSpravniObvodKDatu"/>
			<wsdl:output message="IszrIsuiCtiPrvekSpravniObvodKDatuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrIsuiCtiPrvekSpravniObvodKDatuBinding" type="tns:IszrIsuiCtiPrvekSpravniObvodKDatuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrIsuiCtiPrvekSpravniObvodKDatu">
			<soap:operation soapAction="IszrIsuiCtiPrvekSpravniObvodKDatu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrIsuiCtiPrvekSpravniObvodKDatuService">
		<wsdl:port name="IszrIsuiCtiPrvekSpravniObvodKDatuPortService" binding="tns:IszrIsuiCtiPrvekSpravniObvodKDatuBinding">
			<soap:address location="IszrIsuiCtiPrvekSpravniObvodKDatu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
