<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
	targetNamespace="urn:cz:isvs:iszr:services:IszrRuianCtiAdresu:v1"
	xmlns="urn:cz:isvs:iszr:services:IszrRuianCtiAdresu:v1"
	xmlns:tns="urn:cz:isvs:iszr:services:IszrRuianCtiAdresu:v1"
	xmlns:e36="urn:cz:isvs:iszr:schemas:IszrRuianCtiAdresu:v1"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	name="IszrRuianCtiAdresu">

	<wsdl:documentation>Služba E36 externího rozhraní - Získání adresy adresního místa - RUIAN služba A05.</wsdl:documentation>
	
	<!-- Vývojová verze 0.0.1, 10.06.2011, Aleš Teplý -->
	<!-- Vývojová verze 0.0.2, 28.07.2011, Aleš Teplý, přizpůsobení nové verzi RUIAN -->
	<!-- Fixovaná verze 1.0.0, 07.09.2011, Aleš Teplý -->
	<!-- Katalog.7 verze 1.1.0, 14.03.2012 Aleš Teplý -->
	<!-- AutoCont CZ a.s. -->
	
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="urn:cz:isvs:iszr:schemas:IszrRuianCtiAdresu:v1" schemaLocation="../xsd/IszrRuianCtiAdresu.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="IszrRuianCtiAdresu">
		<wsdl:part name="parametry" element="e36:RuianCtiAdresu"/>
	</wsdl:message>
	<wsdl:message name="IszrRuianCtiAdresuResponse">
		<wsdl:part name="vysledek" element="e36:RuianCtiAdresuResponse"/>
	</wsdl:message>
	<wsdl:portType name="IszrRuianCtiAdresuPortType">
		<wsdl:operation name="IszrRuianCtiAdresu">
			<wsdl:input message="tns:IszrRuianCtiAdresu"/>
			<wsdl:output message="tns:IszrRuianCtiAdresuResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IszrRuianCtiAdresuBinding" type="tns:IszrRuianCtiAdresuPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="IszrRuianCtiAdresu">
			<soap:operation soapAction="IszrRuianCtiAdresu"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IszrRuianCtiAdresuService">
		<wsdl:port name="IszrRuianCtiAdresuPortService" binding="tns:IszrRuianCtiAdresuBinding">
			<soap:address location="IszrRuianCtiAdresu"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>