//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocont.ISZRDemo.IszrAsyncVypisFronty {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:cz:isvs:iszr:services:IszrAsyncVypisFronty:v1", ConfigurationName="IszrAsyncVypisFronty.IszrAsyncVypisFrontyPortType")]
    public interface IszrAsyncVypisFrontyPortType {
        
        // CODEGEN: Generating message contract since the operation IszrAsyncVypisFronty is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="IszrAsyncVypisFronty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IszrOdpovedAbstractType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IdentifikatorRuianType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ZadostInfoType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IszrZadostAsyncAbstractType))]
        Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyResponse IszrAsyncVypisFronty(Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncVypisFronty:v1")]
    public partial class IszrAsyncVypisFrontyType : IszrZadostAsyncAbstractType {
        
        private IszrAsyncVypisFrontyTypeZadost zadostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IszrAsyncVypisFrontyTypeZadost Zadost {
            get {
                return this.zadostField;
            }
            set {
                this.zadostField = value;
                this.RaisePropertyChanged("Zadost");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncVypisFronty:v1")]
    public partial class IszrAsyncVypisFrontyTypeZadost : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OmezeniVypisuType iszrAsyncVypisFrontyDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OmezeniVypisuType IszrAsyncVypisFrontyData {
            get {
                return this.iszrAsyncVypisFrontyDataField;
            }
            set {
                this.iszrAsyncVypisFrontyDataField = value;
                this.RaisePropertyChanged("IszrAsyncVypisFrontyData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncVypisFronty:v1")]
    public partial class OmezeniVypisuType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ulong idTransakceOdField;
        
        private bool idTransakceOdFieldSpecified;
        
        private System.DateTime casVytvoreniOdField;
        
        private bool casVytvoreniOdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ulong IdTransakceOd {
            get {
                return this.idTransakceOdField;
            }
            set {
                this.idTransakceOdField = value;
                this.RaisePropertyChanged("IdTransakceOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdTransakceOdSpecified {
            get {
                return this.idTransakceOdFieldSpecified;
            }
            set {
                this.idTransakceOdFieldSpecified = value;
                this.RaisePropertyChanged("IdTransakceOdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CasVytvoreniOd {
            get {
                return this.casVytvoreniOdField;
            }
            set {
                this.casVytvoreniOdField = value;
                this.RaisePropertyChanged("CasVytvoreniOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CasVytvoreniOdSpecified {
            get {
                return this.casVytvoreniOdFieldSpecified;
            }
            set {
                this.casVytvoreniOdFieldSpecified = value;
                this.RaisePropertyChanged("CasVytvoreniOdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public partial class PolozkaFrontyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kodAsyncSluzbyField;
        
        private string iszrZadostIdField;
        
        private ulong idTransakceField;
        
        private System.DateTime casVytvoreniField;
        
        private System.DateTime casExpiraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN", Order=0)]
        public string KodAsyncSluzby {
            get {
                return this.kodAsyncSluzbyField;
            }
            set {
                this.kodAsyncSluzbyField = value;
                this.RaisePropertyChanged("KodAsyncSluzby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IszrZadostId {
            get {
                return this.iszrZadostIdField;
            }
            set {
                this.iszrZadostIdField = value;
                this.RaisePropertyChanged("IszrZadostId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ulong IdTransakce {
            get {
                return this.idTransakceField;
            }
            set {
                this.idTransakceField = value;
                this.RaisePropertyChanged("IdTransakce");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime CasVytvoreni {
            get {
                return this.casVytvoreniField;
            }
            set {
                this.casVytvoreniField = value;
                this.RaisePropertyChanged("CasVytvoreni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime CasExpirace {
            get {
                return this.casExpiraceField;
            }
            set {
                this.casExpiraceField = value;
                this.RaisePropertyChanged("CasExpirace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncVypisFronty:v1")]
    public partial class PokracovaniVypisuType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool vypisPokracujeField;
        
        private ulong nasledujiciIdTransakceField;
        
        private bool nasledujiciIdTransakceFieldSpecified;
        
        private System.DateTime nasledujiciCasVytvoreniField;
        
        private bool nasledujiciCasVytvoreniFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool VypisPokracuje {
            get {
                return this.vypisPokracujeField;
            }
            set {
                this.vypisPokracujeField = value;
                this.RaisePropertyChanged("VypisPokracuje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ulong NasledujiciIdTransakce {
            get {
                return this.nasledujiciIdTransakceField;
            }
            set {
                this.nasledujiciIdTransakceField = value;
                this.RaisePropertyChanged("NasledujiciIdTransakce");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NasledujiciIdTransakceSpecified {
            get {
                return this.nasledujiciIdTransakceFieldSpecified;
            }
            set {
                this.nasledujiciIdTransakceFieldSpecified = value;
                this.RaisePropertyChanged("NasledujiciIdTransakceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime NasledujiciCasVytvoreni {
            get {
                return this.nasledujiciCasVytvoreniField;
            }
            set {
                this.nasledujiciCasVytvoreniField = value;
                this.RaisePropertyChanged("NasledujiciCasVytvoreni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NasledujiciCasVytvoreniSpecified {
            get {
                return this.nasledujiciCasVytvoreniFieldSpecified;
            }
            set {
                this.nasledujiciCasVytvoreniFieldSpecified = value;
                this.RaisePropertyChanged("NasledujiciCasVytvoreniSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class SystemType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Agenda", typeof(string), DataType="NMTOKEN", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Ais", typeof(int), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Registr", typeof(SystemTypeRegistr), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public enum SystemTypeRegistr {
        
        /// <remarks/>
        ISZR,
        
        /// <remarks/>
        RPP,
        
        /// <remarks/>
        ROB,
        
        /// <remarks/>
        ROS,
        
        /// <remarks/>
        RUIAN,
        
        /// <remarks/>
        ORG,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class StatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VysledekKodType vysledekKodField;
        
        private StatusTypeVysledekDetail[] vysledekDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VysledekKodType VysledekKod {
            get {
                return this.vysledekKodField;
            }
            set {
                this.vysledekKodField = value;
                this.RaisePropertyChanged("VysledekKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VysledekDetail", Order=1)]
        public StatusTypeVysledekDetail[] VysledekDetail {
            get {
                return this.vysledekDetailField;
            }
            set {
                this.vysledekDetailField = value;
                this.RaisePropertyChanged("VysledekDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public enum VysledekKodType {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        CHYBA,
        
        /// <remarks/>
        VAROVANI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class StatusTypeVysledekDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VysledekSubKodType vysledekSubKodField;
        
        private string vysledekPopisField;
        
        private SystemType puvodceField;
        
        private SystemType prijemceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VysledekSubKodType VysledekSubKod {
            get {
                return this.vysledekSubKodField;
            }
            set {
                this.vysledekSubKodField = value;
                this.RaisePropertyChanged("VysledekSubKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VysledekPopis {
            get {
                return this.vysledekPopisField;
            }
            set {
                this.vysledekPopisField = value;
                this.RaisePropertyChanged("VysledekPopis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SystemType Puvodce {
            get {
                return this.puvodceField;
            }
            set {
                this.puvodceField = value;
                this.RaisePropertyChanged("Puvodce");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SystemType Prijemce {
            get {
                return this.prijemceField;
            }
            set {
                this.prijemceField = value;
                this.RaisePropertyChanged("Prijemce");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public enum VysledekSubKodType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PREKROCEN CAS")]
        PREKROCENCAS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PREKROCEN SEZNAM")]
        PREKROCENSEZNAM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NENI OPRAVNENI EGON")]
        NENIOPRAVNENIEGON,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NENI OPRAVNENI")]
        NENIOPRAVNENI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("AIFO NEEXISTUJE")]
        AIFONEEXISTUJE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("AIFO ZRUSENO")]
        AIFOZRUSENO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ZIFO ZRUSENO")]
        ZIFOZRUSENO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ADRESA NEEXISTUJE")]
        ADRESANEEXISTUJE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ADRESA SMAZANA")]
        ADRESASMAZANA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("JENOM ASYNC")]
        JENOMASYNC,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MIMO PORADI")]
        MIMOPORADI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NEPLATNY CAS")]
        NEPLATNYCAS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("STARSI VERZE")]
        STARSIVERZE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NEPLATNA VERZE")]
        NEPLATNAVERZE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DUPLICITNI ZADOST")]
        DUPLICITNIZADOST,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NENI IMPLEMENTOVANO")]
        NENIIMPLEMENTOVANO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NENI K DISPOZICI")]
        NENIKDISPOZICI,
        
        /// <remarks/>
        NENALEZENO,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PROBIHA ZPRACOVANI")]
        PROBIHAZPRACOVANI,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NEVALIDNI DATA")]
        NEVALIDNIDATA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NEVALIDNI ZADOST")]
        NEVALIDNIZADOST,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("APLIKACNI CHYBA")]
        APLIKACNICHYBA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CHYBA VOLANI REGISTRU")]
        CHYBAVOLANIREGISTRU,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CHYBA VOLANI AIS")]
        CHYBAVOLANIAIS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SPECIFIKACE V POPISU")]
        SPECIFIKACEVPOPISU,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class OdpovedInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime casOdpovediField;
        
        private StatusType statusField;
        
        private string agendaZadostIdField;
        
        private string iszrZadostIdField;
        
        private string regOdpovedIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime CasOdpovedi {
            get {
                return this.casOdpovediField;
            }
            set {
                this.casOdpovediField = value;
                this.RaisePropertyChanged("CasOdpovedi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AgendaZadostId {
            get {
                return this.agendaZadostIdField;
            }
            set {
                this.agendaZadostIdField = value;
                this.RaisePropertyChanged("AgendaZadostId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IszrZadostId {
            get {
                return this.iszrZadostIdField;
            }
            set {
                this.iszrZadostIdField = value;
                this.RaisePropertyChanged("IszrZadostId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RegOdpovedId {
            get {
                return this.regOdpovedIdField;
            }
            set {
                this.regOdpovedIdField = value;
                this.RaisePropertyChanged("RegOdpovedId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrOdpovedAifoIdAdrIcoPrvekAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrOdpovedAifoIcoPrvekAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrOdpovedAifoIcoAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrOdpovedIcoAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrOdpovedPrvekAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrOdpovedAifoIdAdrAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrOdpovedIdAdrAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrOdpovedAifoAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrAsyncVypisFrontyResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrOdpovedAbstractType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OdpovedInfoType odpovedInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OdpovedInfoType OdpovedInfo {
            get {
                return this.odpovedInfoField;
            }
            set {
                this.odpovedInfoField = value;
                this.RaisePropertyChanged("OdpovedInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrOdpovedAifoIdAdrIcoPrvekAbstractType : IszrOdpovedAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        private SeznamIdAdresType seznamIdAdresField;
        
        private SeznamIcoTypeIco[] seznamIcoField;
        
        private SeznamPrvkuTypeOdkazRuian[] seznamPrvkuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SeznamIdAdresType SeznamIdAdres {
            get {
                return this.seznamIdAdresField;
            }
            set {
                this.seznamIdAdresField = value;
                this.RaisePropertyChanged("SeznamIdAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ico", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamIcoTypeIco[] SeznamIco {
            get {
                return this.seznamIcoField;
            }
            set {
                this.seznamIcoField = value;
                this.RaisePropertyChanged("SeznamIco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OdkazRuian", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamPrvkuTypeOdkazRuian[] SeznamPrvku {
            get {
                return this.seznamPrvkuField;
            }
            set {
                this.seznamPrvkuField = value;
                this.RaisePropertyChanged("SeznamPrvku");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class MapaAifoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PrevodAifoType[] itemsField;
        
        private int lokalniAifoOdField;
        
        private bool lokalniAifoOdFieldSpecified;
        
        private bool nacistDataField;
        
        private bool nacistDataFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PrevodAifo", Order=0)]
        public PrevodAifoType[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int lokalniAifoOd {
            get {
                return this.lokalniAifoOdField;
            }
            set {
                this.lokalniAifoOdField = value;
                this.RaisePropertyChanged("lokalniAifoOd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lokalniAifoOdSpecified {
            get {
                return this.lokalniAifoOdFieldSpecified;
            }
            set {
                this.lokalniAifoOdFieldSpecified = value;
                this.RaisePropertyChanged("lokalniAifoOdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool nacistData {
            get {
                return this.nacistDataField;
            }
            set {
                this.nacistDataField = value;
                this.RaisePropertyChanged("nacistData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nacistDataSpecified {
            get {
                return this.nacistDataFieldSpecified;
            }
            set {
                this.nacistDataFieldSpecified = value;
                this.RaisePropertyChanged("nacistDataSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class PrevodAifoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LokalniAifoType lokalniAifoField;
        
        private byte[] globalniAifoField;
        
        private string agendaField;
        
        private int aisField;
        
        private bool aisFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LokalniAifoType LokalniAifo {
            get {
                return this.lokalniAifoField;
            }
            set {
                this.lokalniAifoField = value;
                this.RaisePropertyChanged("LokalniAifo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] GlobalniAifo {
            get {
                return this.globalniAifoField;
            }
            set {
                this.globalniAifoField = value;
                this.RaisePropertyChanged("GlobalniAifo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string agenda {
            get {
                return this.agendaField;
            }
            set {
                this.agendaField = value;
                this.RaisePropertyChanged("agenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ais {
            get {
                return this.aisField;
            }
            set {
                this.aisField = value;
                this.RaisePropertyChanged("ais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aisSpecified {
            get {
                return this.aisFieldSpecified;
            }
            set {
                this.aisFieldSpecified = value;
                this.RaisePropertyChanged("aisSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class LokalniAifoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PrevodAifoStatusType prevodAifoStatusField;
        
        private bool prevodAifoStatusFieldSpecified;
        
        private bool stavOvereniAifoField;
        
        private bool stavOvereniAifoFieldSpecified;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PrevodAifoStatusType prevodAifoStatus {
            get {
                return this.prevodAifoStatusField;
            }
            set {
                this.prevodAifoStatusField = value;
                this.RaisePropertyChanged("prevodAifoStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prevodAifoStatusSpecified {
            get {
                return this.prevodAifoStatusFieldSpecified;
            }
            set {
                this.prevodAifoStatusFieldSpecified = value;
                this.RaisePropertyChanged("prevodAifoStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool stavOvereniAifo {
            get {
                return this.stavOvereniAifoField;
            }
            set {
                this.stavOvereniAifoField = value;
                this.RaisePropertyChanged("stavOvereniAifo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stavOvereniAifoSpecified {
            get {
                return this.stavOvereniAifoFieldSpecified;
            }
            set {
                this.stavOvereniAifoFieldSpecified = value;
                this.RaisePropertyChanged("stavOvereniAifoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public enum PrevodAifoStatusType {
        
        /// <remarks/>
        AifoZdrojNenalezeno,
        
        /// <remarks/>
        AifoZdrojNeplatne,
        
        /// <remarks/>
        AifoCilNeexistuje,
        
        /// <remarks/>
        AifoCilNeplatne,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class SeznamIdAdresType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SeznamIdAdresTypeAdresniMisto[] adresniMistoField;
        
        private SeznamIdAdresTypeAdresniLokalita[] adresniLokalitaField;
        
        private bool nacistDataField;
        
        private bool nacistDataFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdresniMisto", Order=0)]
        public SeznamIdAdresTypeAdresniMisto[] AdresniMisto {
            get {
                return this.adresniMistoField;
            }
            set {
                this.adresniMistoField = value;
                this.RaisePropertyChanged("AdresniMisto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdresniLokalita", Order=1)]
        public SeznamIdAdresTypeAdresniLokalita[] AdresniLokalita {
            get {
                return this.adresniLokalitaField;
            }
            set {
                this.adresniLokalitaField = value;
                this.RaisePropertyChanged("AdresniLokalita");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool nacistData {
            get {
                return this.nacistDataField;
            }
            set {
                this.nacistDataField = value;
                this.RaisePropertyChanged("nacistData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nacistDataSpecified {
            get {
                return this.nacistDataFieldSpecified;
            }
            set {
                this.nacistDataFieldSpecified = value;
                this.RaisePropertyChanged("nacistDataSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class SeznamIdAdresTypeAdresniMisto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StavOvereniPrvkuRuianType stavOvereniPrvkuField;
        
        private bool stavOvereniPrvkuFieldSpecified;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StavOvereniPrvkuRuianType stavOvereniPrvku {
            get {
                return this.stavOvereniPrvkuField;
            }
            set {
                this.stavOvereniPrvkuField = value;
                this.RaisePropertyChanged("stavOvereniPrvku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stavOvereniPrvkuSpecified {
            get {
                return this.stavOvereniPrvkuFieldSpecified;
            }
            set {
                this.stavOvereniPrvkuFieldSpecified = value;
                this.RaisePropertyChanged("stavOvereniPrvkuSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public enum StavOvereniPrvkuRuianType {
        
        /// <remarks/>
        existuje,
        
        /// <remarks/>
        nenalezen,
        
        /// <remarks/>
        zrusen,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class SeznamIdAdresTypeAdresniLokalita : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StavOvereniPrvkuRuianType stavOvereniPrvkuField;
        
        private bool stavOvereniPrvkuFieldSpecified;
        
        private TypAdresniLokalityType typPrvkuField;
        
        private int valueField;
        
        public SeznamIdAdresTypeAdresniLokalita() {
            this.typPrvkuField = TypAdresniLokalityType.OB;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StavOvereniPrvkuRuianType stavOvereniPrvku {
            get {
                return this.stavOvereniPrvkuField;
            }
            set {
                this.stavOvereniPrvkuField = value;
                this.RaisePropertyChanged("stavOvereniPrvku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stavOvereniPrvkuSpecified {
            get {
                return this.stavOvereniPrvkuFieldSpecified;
            }
            set {
                this.stavOvereniPrvkuFieldSpecified = value;
                this.RaisePropertyChanged("stavOvereniPrvkuSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(TypAdresniLokalityType.OB)]
        public TypAdresniLokalityType typPrvku {
            get {
                return this.typPrvkuField;
            }
            set {
                this.typPrvkuField = value;
                this.RaisePropertyChanged("typPrvku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public enum TypAdresniLokalityType {
        
        /// <remarks/>
        OB,
        
        /// <remarks/>
        MP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class SeznamIcoTypeIco : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool stavOvereniIcoField;
        
        private bool stavOvereniIcoFieldSpecified;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool stavOvereniIco {
            get {
                return this.stavOvereniIcoField;
            }
            set {
                this.stavOvereniIcoField = value;
                this.RaisePropertyChanged("stavOvereniIco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stavOvereniIcoSpecified {
            get {
                return this.stavOvereniIcoFieldSpecified;
            }
            set {
                this.stavOvereniIcoFieldSpecified = value;
                this.RaisePropertyChanged("stavOvereniIcoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class SeznamPrvkuTypeOdkazRuian : IdentifikatorRuianType {
        
        private StavOvereniPrvkuRuianType stavOvereniPrvkuField;
        
        private bool stavOvereniPrvkuFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StavOvereniPrvkuRuianType stavOvereniPrvku {
            get {
                return this.stavOvereniPrvkuField;
            }
            set {
                this.stavOvereniPrvkuField = value;
                this.RaisePropertyChanged("stavOvereniPrvku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stavOvereniPrvkuSpecified {
            get {
                return this.stavOvereniPrvkuFieldSpecified;
            }
            set {
                this.stavOvereniPrvkuFieldSpecified = value;
                this.RaisePropertyChanged("stavOvereniPrvkuSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class IdentifikatorRuianType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kodPrvkuField;
        
        private TypPrvkuRuianType typPrvkuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN", Order=0)]
        public string KodPrvku {
            get {
                return this.kodPrvkuField;
            }
            set {
                this.kodPrvkuField = value;
                this.RaisePropertyChanged("KodPrvku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TypPrvkuRuianType TypPrvku {
            get {
                return this.typPrvkuField;
            }
            set {
                this.typPrvkuField = value;
                this.RaisePropertyChanged("TypPrvku");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public enum TypPrvkuRuianType {
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        AD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrOdpovedAifoIcoPrvekAbstractType : IszrOdpovedAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        private SeznamIcoTypeIco[] seznamIcoField;
        
        private SeznamPrvkuTypeOdkazRuian[] seznamPrvkuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ico", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamIcoTypeIco[] SeznamIco {
            get {
                return this.seznamIcoField;
            }
            set {
                this.seznamIcoField = value;
                this.RaisePropertyChanged("SeznamIco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OdkazRuian", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamPrvkuTypeOdkazRuian[] SeznamPrvku {
            get {
                return this.seznamPrvkuField;
            }
            set {
                this.seznamPrvkuField = value;
                this.RaisePropertyChanged("SeznamPrvku");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrOdpovedAifoIcoAbstractType : IszrOdpovedAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        private SeznamIcoTypeIco[] seznamIcoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ico", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamIcoTypeIco[] SeznamIco {
            get {
                return this.seznamIcoField;
            }
            set {
                this.seznamIcoField = value;
                this.RaisePropertyChanged("SeznamIco");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrOdpovedIcoAbstractType : IszrOdpovedAbstractType {
        
        private SeznamIcoTypeIco[] seznamIcoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ico", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamIcoTypeIco[] SeznamIco {
            get {
                return this.seznamIcoField;
            }
            set {
                this.seznamIcoField = value;
                this.RaisePropertyChanged("SeznamIco");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrOdpovedPrvekAbstractType : IszrOdpovedAbstractType {
        
        private SeznamPrvkuTypeOdkazRuian[] seznamPrvkuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OdkazRuian", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamPrvkuTypeOdkazRuian[] SeznamPrvku {
            get {
                return this.seznamPrvkuField;
            }
            set {
                this.seznamPrvkuField = value;
                this.RaisePropertyChanged("SeznamPrvku");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrOdpovedAifoIdAdrAbstractType : IszrOdpovedAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        private SeznamIdAdresType seznamIdAdresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SeznamIdAdresType SeznamIdAdres {
            get {
                return this.seznamIdAdresField;
            }
            set {
                this.seznamIdAdresField = value;
                this.RaisePropertyChanged("SeznamIdAdres");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrOdpovedIdAdrAbstractType : IszrOdpovedAbstractType {
        
        private SeznamIdAdresType seznamIdAdresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SeznamIdAdresType SeznamIdAdres {
            get {
                return this.seznamIdAdresField;
            }
            set {
                this.seznamIdAdresField = value;
                this.RaisePropertyChanged("SeznamIdAdres");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrOdpovedAifoAbstractType : IszrOdpovedAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncVypisFronty:v1")]
    public partial class IszrAsyncVypisFrontyResponseType : IszrOdpovedAbstractType {
        
        private IszrAsyncVypisFrontyResponseTypeIszrOdpoved iszrOdpovedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IszrAsyncVypisFrontyResponseTypeIszrOdpoved IszrOdpoved {
            get {
                return this.iszrOdpovedField;
            }
            set {
                this.iszrOdpovedField = value;
                this.RaisePropertyChanged("IszrOdpoved");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncVypisFronty:v1")]
    public partial class IszrAsyncVypisFrontyResponseTypeIszrOdpoved : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IszrAsyncVypisFrontyResponseTypeIszrOdpovedIszrAsyncVypisFrontyDataResponse iszrAsyncVypisFrontyDataResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IszrAsyncVypisFrontyResponseTypeIszrOdpovedIszrAsyncVypisFrontyDataResponse IszrAsyncVypisFrontyDataResponse {
            get {
                return this.iszrAsyncVypisFrontyDataResponseField;
            }
            set {
                this.iszrAsyncVypisFrontyDataResponseField = value;
                this.RaisePropertyChanged("IszrAsyncVypisFrontyDataResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncVypisFronty:v1")]
    public partial class IszrAsyncVypisFrontyResponseTypeIszrOdpovedIszrAsyncVypisFrontyDataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PokracovaniVypisuType iszrAplikacniStatusField;
        
        private PolozkaFrontyType[] polozkyFrontyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PokracovaniVypisuType IszrAplikacniStatus {
            get {
                return this.iszrAplikacniStatusField;
            }
            set {
                this.iszrAplikacniStatusField = value;
                this.RaisePropertyChanged("IszrAplikacniStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PolozkaFronty", IsNullable=false)]
        public PolozkaFrontyType[] PolozkyFronty {
            get {
                return this.polozkyFrontyField;
            }
            set {
                this.polozkyFrontyField = value;
                this.RaisePropertyChanged("PolozkyFronty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public partial class AutorizaceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int maximalniPocetZaznamuField;
        
        private bool maximalniPocetZaznamuFieldSpecified;
        
        private string seznamUdajuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MaximalniPocetZaznamu {
            get {
                return this.maximalniPocetZaznamuField;
            }
            set {
                this.maximalniPocetZaznamuField = value;
                this.RaisePropertyChanged("MaximalniPocetZaznamu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaximalniPocetZaznamuSpecified {
            get {
                return this.maximalniPocetZaznamuFieldSpecified;
            }
            set {
                this.maximalniPocetZaznamuFieldSpecified = value;
                this.RaisePropertyChanged("MaximalniPocetZaznamuSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SeznamUdaju {
            get {
                return this.seznamUdajuField;
            }
            set {
                this.seznamUdajuField = value;
                this.RaisePropertyChanged("SeznamUdaju");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ZadostInfoIszrType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1")]
    public partial class ZadostInfoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime casZadostiField;
        
        private string agendaField;
        
        private string agendovaRoleField;
        
        private string ovmField;
        
        private int aisField;
        
        private bool aisFieldSpecified;
        
        private string subjektField;
        
        private string uzivatelField;
        
        private string duvodUcelField;
        
        private string agendaZadostIdField;
        
        private string predchoziZadostIdField;
        
        private string iszrZadostIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime CasZadosti {
            get {
                return this.casZadostiField;
            }
            set {
                this.casZadostiField = value;
                this.RaisePropertyChanged("CasZadosti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN", Order=1)]
        public string Agenda {
            get {
                return this.agendaField;
            }
            set {
                this.agendaField = value;
                this.RaisePropertyChanged("Agenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN", Order=2)]
        public string AgendovaRole {
            get {
                return this.agendovaRoleField;
            }
            set {
                this.agendovaRoleField = value;
                this.RaisePropertyChanged("AgendovaRole");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN", Order=3)]
        public string Ovm {
            get {
                return this.ovmField;
            }
            set {
                this.ovmField = value;
                this.RaisePropertyChanged("Ovm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Ais {
            get {
                return this.aisField;
            }
            set {
                this.aisField = value;
                this.RaisePropertyChanged("Ais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AisSpecified {
            get {
                return this.aisFieldSpecified;
            }
            set {
                this.aisFieldSpecified = value;
                this.RaisePropertyChanged("AisSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Subjekt {
            get {
                return this.subjektField;
            }
            set {
                this.subjektField = value;
                this.RaisePropertyChanged("Subjekt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Uzivatel {
            get {
                return this.uzivatelField;
            }
            set {
                this.uzivatelField = value;
                this.RaisePropertyChanged("Uzivatel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DuvodUcel {
            get {
                return this.duvodUcelField;
            }
            set {
                this.duvodUcelField = value;
                this.RaisePropertyChanged("DuvodUcel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AgendaZadostId {
            get {
                return this.agendaZadostIdField;
            }
            set {
                this.agendaZadostIdField = value;
                this.RaisePropertyChanged("AgendaZadostId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PredchoziZadostId {
            get {
                return this.predchoziZadostIdField;
            }
            set {
                this.predchoziZadostIdField = value;
                this.RaisePropertyChanged("PredchoziZadostId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string IszrZadostId {
            get {
                return this.iszrZadostIdField;
            }
            set {
                this.iszrZadostIdField = value;
                this.RaisePropertyChanged("IszrZadostId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public partial class ZadostInfoIszrType : ZadostInfoType {
        
        private int prioritaAisField;
        
        private bool prioritaAisFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PrioritaAis {
            get {
                return this.prioritaAisField;
            }
            set {
                this.prioritaAisField = value;
                this.RaisePropertyChanged("PrioritaAis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritaAisSpecified {
            get {
                return this.prioritaAisFieldSpecified;
            }
            set {
                this.prioritaAisFieldSpecified = value;
                this.RaisePropertyChanged("PrioritaAisSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostAifoAsyncAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostAifoIcoAsyncAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostRAifoAsyncAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostAifoIcoPrvekAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostAifoIcoAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostIcoAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostPrvekAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostAifoIdAdrAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostRIdAdrAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostIdAdrAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostRAifoAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostAifoAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrAsyncVypisFrontyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostAsyncAbstractType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZadostInfoIszrType zadostInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ZadostInfoIszrType ZadostInfo {
            get {
                return this.zadostInfoField;
            }
            set {
                this.zadostInfoField = value;
                this.RaisePropertyChanged("ZadostInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostAifoAsyncAbstractType : IszrZadostAsyncAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostAifoIcoAsyncAbstractType : IszrZadostAsyncAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        private SeznamIcoTypeIco[] seznamIcoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ico", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamIcoTypeIco[] SeznamIco {
            get {
                return this.seznamIcoField;
            }
            set {
                this.seznamIcoField = value;
                this.RaisePropertyChanged("SeznamIco");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostRAifoAsyncAbstractType : IszrZadostAsyncAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostAifoIcoPrvekAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostAifoIcoAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostIcoAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostPrvekAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostAifoIdAdrAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostRIdAdrAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostIdAdrAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostRAifoAbstractType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IszrZadostAifoAbstractType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostAbstractType : IszrZadostAsyncAbstractType {
        
        private AutorizaceType autorizaceInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AutorizaceType AutorizaceInfo {
            get {
                return this.autorizaceInfoField;
            }
            set {
                this.autorizaceInfoField = value;
                this.RaisePropertyChanged("AutorizaceInfo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostAifoIcoPrvekAbstractType : IszrZadostAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        private SeznamIcoTypeIco[] seznamIcoField;
        
        private SeznamPrvkuTypeOdkazRuian[] seznamPrvkuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ico", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamIcoTypeIco[] SeznamIco {
            get {
                return this.seznamIcoField;
            }
            set {
                this.seznamIcoField = value;
                this.RaisePropertyChanged("SeznamIco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OdkazRuian", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamPrvkuTypeOdkazRuian[] SeznamPrvku {
            get {
                return this.seznamPrvkuField;
            }
            set {
                this.seznamPrvkuField = value;
                this.RaisePropertyChanged("SeznamPrvku");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostAifoIcoAbstractType : IszrZadostAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        private SeznamIcoTypeIco[] seznamIcoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ico", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamIcoTypeIco[] SeznamIco {
            get {
                return this.seznamIcoField;
            }
            set {
                this.seznamIcoField = value;
                this.RaisePropertyChanged("SeznamIco");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostIcoAbstractType : IszrZadostAbstractType {
        
        private SeznamIcoTypeIco[] seznamIcoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Ico", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamIcoTypeIco[] SeznamIco {
            get {
                return this.seznamIcoField;
            }
            set {
                this.seznamIcoField = value;
                this.RaisePropertyChanged("SeznamIco");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostPrvekAbstractType : IszrZadostAbstractType {
        
        private SeznamPrvkuTypeOdkazRuian[] seznamPrvkuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OdkazRuian", Namespace="urn:cz:isvs:reg:schemas:RegTypy:v1", IsNullable=false)]
        public SeznamPrvkuTypeOdkazRuian[] SeznamPrvku {
            get {
                return this.seznamPrvkuField;
            }
            set {
                this.seznamPrvkuField = value;
                this.RaisePropertyChanged("SeznamPrvku");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostAifoIdAdrAbstractType : IszrZadostAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        private SeznamIdAdresType seznamIdAdresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SeznamIdAdresType SeznamIdAdres {
            get {
                return this.seznamIdAdresField;
            }
            set {
                this.seznamIdAdresField = value;
                this.RaisePropertyChanged("SeznamIdAdres");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostRIdAdrAbstractType : IszrZadostAbstractType {
        
        private SeznamIdAdresType seznamIdAdresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SeznamIdAdresType SeznamIdAdres {
            get {
                return this.seznamIdAdresField;
            }
            set {
                this.seznamIdAdresField = value;
                this.RaisePropertyChanged("SeznamIdAdres");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostIdAdrAbstractType : IszrZadostAbstractType {
        
        private SeznamIdAdresType seznamIdAdresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SeznamIdAdresType SeznamIdAdres {
            get {
                return this.seznamIdAdresField;
            }
            set {
                this.seznamIdAdresField = value;
                this.RaisePropertyChanged("SeznamIdAdres");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostRAifoAbstractType : IszrZadostAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAbstract:v1")]
    public abstract partial class IszrZadostAifoAbstractType : IszrZadostAbstractType {
        
        private MapaAifoType mapaAifoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MapaAifoType MapaAifo {
            get {
                return this.mapaAifoField;
            }
            set {
                this.mapaAifoField = value;
                this.RaisePropertyChanged("MapaAifo");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IszrAsyncVypisFrontyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncVypisFronty:v1", Order=0)]
        public Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyType IszrAsyncVypisFronty;
        
        public IszrAsyncVypisFrontyRequest() {
        }
        
        public IszrAsyncVypisFrontyRequest(Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyType IszrAsyncVypisFronty) {
            this.IszrAsyncVypisFronty = IszrAsyncVypisFronty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IszrAsyncVypisFrontyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IszrAsyncVypisFrontyResponse", Namespace="urn:cz:isvs:iszr:schemas:IszrAsyncVypisFronty:v1", Order=0)]
        public Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyResponseType IszrAsyncVypisFrontyResponse1;
        
        public IszrAsyncVypisFrontyResponse() {
        }
        
        public IszrAsyncVypisFrontyResponse(Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyResponseType IszrAsyncVypisFrontyResponse1) {
            this.IszrAsyncVypisFrontyResponse1 = IszrAsyncVypisFrontyResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IszrAsyncVypisFrontyPortTypeChannel : Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IszrAsyncVypisFrontyPortTypeClient : System.ServiceModel.ClientBase<Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyPortType>, Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyPortType {
        
        public IszrAsyncVypisFrontyPortTypeClient() {
        }
        
        public IszrAsyncVypisFrontyPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IszrAsyncVypisFrontyPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IszrAsyncVypisFrontyPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IszrAsyncVypisFrontyPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyResponse Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyPortType.IszrAsyncVypisFronty(Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyRequest request) {
            return base.Channel.IszrAsyncVypisFronty(request);
        }
        
        public Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyResponseType IszrAsyncVypisFronty(Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyType IszrAsyncVypisFronty1) {
            Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyRequest inValue = new Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyRequest();
            inValue.IszrAsyncVypisFronty = IszrAsyncVypisFronty1;
            Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyResponse retVal = ((Autocont.ISZRDemo.IszrAsyncVypisFronty.IszrAsyncVypisFrontyPortType)(this)).IszrAsyncVypisFronty(inValue);
            return retVal.IszrAsyncVypisFrontyResponse1;
        }
    }
}
